### ISSUE TITLE
zlib: Resetter inteface not implemented by reader

### ISSUE THREAD

**Issue by codesoap** [klauspost/compress#1015]
The `zlib.NewReader` and `zlib.NewReaderDict` functions claim in their documentation, that they implement `zlib.Resetter`, yet they return an `io.ReadCloser`. An `io.ReadCloser` does not have a `Reset` method, so it's impossible to use it as a `zlib.Resetter`. Consequently, this fails with the compile error `r.Reset undefined (type io.ReadCloser has no field or method Reset)`:

```go
r, err := zlib.NewReader(bytes.NewReader([]byte{49}))
if err != nil {
	panic(err)
}
err = r.Reset(bytes.NewReader([]byte{50}), nil)
if err != nil {
	panic(err)
}
```

https://go.dev/play/p/AGq97p0ZQky

Am I missing something, or is this an error in the design of the zlib package?

**Comment by klauspost** [comment]
You must check for the interface yourself: https://go.dev/play/p/cS7WEidRgRs

**Comment by codesoap** [comment]
Ah, I didn't think of that. Thanks!
