### ISSUE TITLE
EncodeAll doesn't write Frame_Content_Size if payload is small

### ISSUE THREAD

**Issue by RPGillespie6** [klauspost/compress#1027]
I have a web service using this in a middleware to compress http responses. The client is a .NET application using [ZstdNet](https://github.com/skbkontur/ZstdNet). The problem is that the .NET client has a constraint where it has to use [Decompressor.Unwrap](https://github.com/skbkontur/ZstdNet?tab=readme-ov-file#decompressor-class), which appears to only support [size-specified](https://github.com/skbkontur/ZstdNet/blob/7a4de80feb49b9810958c7def59d6642f1b1ba9f/ZstdNet/Decompressor.cs#L71) and single frame payloads.

If I use:
```
enc, _ := zstd.NewWriter(nil)
compressed := enc.EncodeAll(b, nil)
```

Then it appears that the resulting compressed bytes usually are single frame and have `Frame_Content_Size` set. However, if `b` is small (haven't confirmed, but possibly [1KB](https://github.com/klauspost/compress/blob/4d8527ad8853969c42e45a0da335c3e79223983a/zstd/framedec.go#L39)), then then `Frame_Content_Size` bytes are not written out in the zstd header and `Decompressor.Unwrap` doesn't know how much memory to allocate and throws.

Is there a way to ensure `Frame_Content_Size` always gets written and that the result is single frame (assuming decompressed payload is <2GB)?

**Comment by RPGillespie6** [comment]
Actually, after digging through the code, I believe this solves my issue:

```
enc, _ := zstd.NewWriter(nil, zstd.WithSingleSegment(true))
// ...
```

**Comment by klauspost** [comment]
Yes. The limit is 256 bytes. When "down there" every byte counts, since it is proportionally expensive. So it is only stored if "Single Segment" is requested, indicating that this is a priority.
