### ISSUE TITLE
Cannot be used with Modules enabled?

### ISSUE THREAD

**Issue by fd0** [klauspost/compress#121]
First, I'd like to thank you very much for your work!

I'm unable to use this library when Go Modules are enabled (using Go 1.12):

```
$ export GOPATH=$(mktemp -d)
$ export GO111MODULE=on

$ cat main.go
package main

import (
	. "github.com/klauspost/compress/zstd"
)

func main() {
}

$ go mod init github.com/fd0/zstdtest

$ go get github.com/klauspost/compress
go: finding github.com/klauspost/compress v1.7.0
go: downloading github.com/klauspost/compress v1.7.0
go: extracting github.com/klauspost/compress v1.7.0

$ go build
go: finding github.com/cespare/xxhash v1.1.0
go: downloading github.com/cespare/xxhash v1.1.0
go: extracting github.com/cespare/xxhash v1.1.0
go: finding github.com/OneOfOne/xxhash v1.2.2
go: finding github.com/spaolacci/murmur3 v0.0.0-20180118202830-f09979ecbc72
# github.com/klauspost/compress/zstd
/tmp/tmp.66p2ytn1dg/pkg/mod/github.com/klauspost/compress@v1.7.0/zstd/enc_fast.go:32:15: undefined: xxhash.Digest

```

As far as I can see the reason is that while your package hasn't adopted Go Modules yet, the `xxhash` package has and is already at v2.0.0 and the `zstd` package depends on functionality not available in versions < v2.0.0.

So the following happens:
 * In non-Go-Module mode (`GOPATH`-mode), the master branch of the `xxhash` package is used, which is at v2.0.0, so the code compiles
 * In Module mode, my program gets `compress` at version v1.7.0. The toolchain detects that it depends on `github.com/cespare/xxhash`. That library has opted in to Go Modules, under which the import path `github.com/cespare/xxhash` is only valid for versions v0.x.x and v1.x.x. So the toolchain selects `v1.1.0`. But the API used by the `zstd` package is only available in v2.0.0, and the build fails.

The only solution (as far as I can see) is [to opt into Go Modules](https://gist.github.com/32369c595ce9bafc47453170d7c56580):
 * In Module mode, the toolchain sees the requirement for v2.0.0 of `xxhash`, gets it and the build just works
 * In non-Module mode, the older versions of Go (starting at 1.9.7 and 1.10.3) have been patched to support dropping the `/v2` at the end of the import path, so the toolchain will just get the master branch of the `xxhash` package and it also works. I've verified this using Go 1.12 and Go 1.9.7. Building with older versions (< 1.9.7 or < 1.10.3) [fails](https://gist.github.com/b977259ec9cdd0471b21cb72292205d6) though, although this could maybe be fixed by the author of the `xxhash` package.

Please let me know if you'd like me to submit this as a pull request :)

**Comment by klauspost** [comment]
I don't have a huge problem with modules, but I don't want to have 'Datadog/zstd' in there.

I might move forward with #120 which should also move the dependency.

**Comment by klauspost** [comment]
Merged #122 which should get rid of the Datadog and go-cmp references.

This of course also means that you will have to manually update the package, but I guess you are used to this if you already use modules.

**Comment by fd0** [comment]
> I don't want to have 'Datadog/zstd' in there.

Oh, I can understand that. As far as I understood, the `go.mod` is only a declaration of required minimum versions, not a list of module to fetch and always include in builds. I've locally converted your library to Go Modules and built a binary with it:
```
$ cat go.mod
module foo

go 1.12

require github.com/klauspost/compress v1.7.0

replace github.com/klauspost/compress => ../compress
```

The `compress` library contains the following `go.mod`:

```
$ cat ../compress/go.mod
module github.com/klauspost/compress

go 1.12

require (
	github.com/DataDog/zstd v1.4.0
	github.com/cespare/xxhash v1.1.0 // indirect
	github.com/cespare/xxhash/v2 v2.0.0
	github.com/google/go-cmp v0.3.0
	github.com/klauspost/cpuid v1.2.1
)
```

As you can see there's `DataDog/zstd` in it (because the tests for `compress` need it), but if I build a binary (explicitly disabling cgo), that library is fetched but neither compiled not included in the final binary:

```
$ CGO_ENABLED=0 go build
go: finding github.com/DataDog/zstd v1.4.0
go: finding github.com/cespare/xxhash/v2 v2.0.0
go: finding github.com/cespare/xxhash v1.1.0
go: finding github.com/google/go-cmp v0.3.0
go: finding github.com/klauspost/cpuid v1.2.1
go: finding github.com/OneOfOne/xxhash v1.2.2
go: finding github.com/spaolacci/murmur3 v0.0.0-20180118202830-f09979ecbc72
go: downloading github.com/cespare/xxhash v1.1.0
go: extracting github.com/cespare/xxhash v1.1.0
go: downloading github.com/cespare/xxhash/v2 v2.0.0
go: extracting github.com/cespare/xxhash/v2 v2.0.0

$ goversion -mh foo
foo go1.12.5
	path  foo
	mod   foo                            (devel)
	dep   github.com/cespare/xxhash/v2   v2.0.0   h1:Eb1IiuHmi3FhT12NKfqCQXSXRqc4NTMvgJoREemrSt4=
	dep   github.com/klauspost/compress  v1.7.0
	=>    ../compress

$ file foo
foo: ELF 64-bit LSB executable, x86-64, version 1 (SYSV), statically linked, Go BuildID=nFVqtRIjMrJgNCVytCP-/r7IFpZfFFtSf5M-BpMBX/LrQTddp-pm2ldq7u-TgQ/DTsVDKiTtOUlK6TiNCib, not stripped
```

> What is the impact of opting in on modules? Can I still have my stuff in gopath?

Sure, it'll just work as long as you use Go >= 1.9.7, Go >= 1.10.3 or Go 1.11 or Go 1.12 and everything thereafter. For Go 1.13, you will probably need to explicitly disable Module support (probably via `GO111MODULE=off` or so), because that will be on by default then.

> I honestly haven't spent too much time on it, and these issues doesn't make me in a good mood for it.

I can totally understand that, and the transition period will not be completely painless. The Go team works very hard to avoid another Python2/3 or Ruby 1.8/1.9 split of the ecosystem. In my personal experience, Modules work great for most use cases, this issue is a rather peculiar corner case (in my opinion). :)

**Comment by fd0** [comment]
For the latest master branch (91344b7c64041549c76c156d59e6c4f4429b66f7) you would need to the following in order to switch on Go Modules:
 * run `go mod init` (it should figure out the Module path itself, otherwise run `go mod init github.com/klauspost/compress`)
 * run `sed -i 's,cespare/xxhash,cespare/xxhash/v2,g' zstd/*.go` to add the `/v2` suffix to the import path of the `xxhash` module

At that point you can build the code and run the tests with Go Modules switched on via `GO111MODULE=on go test -v` and it'll populate the `go.mod` with the detected dependencies. The `DataDog/zstd` package is still used by the tests in `decoder_test.go` and `go-cmp` is used by `fse/fse_test.go` so they are still included. If you don't like that in your `go.mod`, you'd need to remove the libraries from the tests.

You can then run `GO111MODULE=on go mod tidy` to clean up both files and commit `go.mod` and `go.sum` to the repo. If you're satisfied, release a new version (e.g. 1.7.1 or so).

FYI: Go Module support is set to `auto` by default, which means it is considered `off` when the current working directory is below `GOPATH/src` and `on` otherwise.

Please let me know if I can be of any help, or if you have further questions! I'm not an expert on the Go Module stuff, but I'll try to help as best as I can :)

**Comment by klauspost** [comment]
Would #123 work for you?

It eliminates two further dependencies only used for `xxhash` tests anyway - and I'm really not ready for modules yet ;)

**Comment by klauspost** [comment]
I have merged it. Feel free to close the issue if this works for you.

**Comment by mholt** [comment]
Works for me! Thank you.

**Comment by fd0** [comment]
Works for me too! Now it'd be nice to tag v1.7.1 or so, the release will be found by the Go toolchain automatically :)

Thanks a lot!

**Comment by klauspost** [comment]
@fd0 I will - but I have a decoder error I would like to have worked out before that - #124

**Comment by fd0** [comment]
Oh, sure! Don't hurry anything :)
