### ISSUE TITLE
timeout in zstd/encoder_test.go:100 on ARM Cortex-A9

### ISSUE THREAD

**Issue by rathann** [klauspost/compress#165]
The whole zst test takes over 120s total on an ARM Cortex-A9:
```
ok  	github.com/klauspost/compress/zstd	122.090s
```
I experimented with setting different timeout values in [zstd/encoder_test.go:100](https://github.com/klauspost/compress/blob/master/zstd/encoder_test.go#L100) and found that 35 seconds is enough for this particular hardware, but you might want to increase it further to have some headroom for slower hardware.

**Comment by klauspost** [comment]
Thanks for the report. Set the timeout to 2 minutes.
