### ISSUE TITLE
zstd: read blocking when unable to fill buffer

### ISSUE THREAD

**Issue by vcabbage** [klauspost/compress#168]
I ran into an scenario where my application would block when a `zstd.Reader` was wrapped with a `bufio.Reader`. When there was data available but less than the 4KB buffer that `bufio.Reader` uses `zstd.Reader.Read` appears to block waiting for more.

I can work around this easily by not using a `bufio.Reader` or passing the `buio.Reader` to `zstd.NewReader`, but I was wondering if my interpretation of the code sounds right to you and whether you intended this behavior.

`io.Reader` docs say "Read conventionally returns what is available instead of waiting for more" so it was slightly surprising but it's not a requirement so I wouldn't call this a bug.

Thank you for all the work you've put into these compression libraries, they're really great!

**Comment by klauspost** [comment]
When decoding data needs to be available in blocks. This means it is impossible for the decoder to progress until an entire block is available.

To force all data to be output, you can use the [Flush](https://godoc.org/github.com/klauspost/compress/zstd#Encoder.Flush) function when encoding to force a block break at a specific point.

**Comment by vcabbage** [comment]
Thanks for the quick response. I am using `Flush` when writing data.

**Comment by klauspost** [comment]
ok. I don't remember there being a buffer in the decoder. I can easily have forgotten it, though.

**Comment by vcabbage** [comment]
I may be misreading, but this section appears to continue to try to read blocks until `p` is filled or an error is encountered.

https://github.com/klauspost/compress/blob/36d74a08c1195867b733b78c4cb2ee2d08b3c3e8/zstd/decoder.go#L112-L129

My applications stack trace shows it blocking on https://github.com/klauspost/compress/blob/36d74a08c1195867b733b78c4cb2ee2d08b3c3e8/zstd/decoder.go#L344

So I don't confuse things, only my code is using a `bufio.Reader`.

**Comment by klauspost** [comment]
Ok, I see. Yeah - we don't know if `d.nextBlock()` will block. 

Usually it will not. It should be fairly trivial to add a default select [here](https://github.com/klauspost/compress/blob/master/zstd/decoder.go#L344) that just whether data is available. Maybe change the signature to `func (d *Decoder) nextBlock(block bool) bool`

Calls from `WriteTo` should be blocking. As should calls from `Read` when no data has been put into the buffer IMO.

**Comment by klauspost** [comment]
Fixed in master. Released as v1.8.6

**Comment by vcabbage** [comment]
Thank you!

FWIW, I agree with:
>Calls from `WriteTo` should be blocking. As should calls from `Read` when no data has been put into the buffer IMO.

The `io.Reader` docs also discourage returning `0, nil` unless the slice passed in has a length of 0.
