### ISSUE TITLE
Decoding error (36) : Corrupted block detected

### ISSUE THREAD

**Issue by fproulx-eoscanada** [klauspost/compress#170]
Hello,

I am unable to decompress some (like one out of several thousands) of files compressed using your library in `*.tar.zst` (I use `mholt/archiver`, which uses your lib as backend). We have forked `mholt` to update to `v1.8.6`, still the same isssue.

The error we get with `unzstd` is `Decoding error (36) : Corrupted block detected`

**Comment by klauspost** [comment]
Is it possible share a sample?

Maybe email a link to klauspost@gmail.com if you want to keep it private.

**Comment by fproulx-eoscanada** [comment]
Will do.

**Comment by fproulx-eoscanada** [comment]
@abourget ^

**Comment by klauspost** [comment]
Thanks!

**Comment by klauspost** [comment]
This seems to go back to #146 and possibly outputting too much data if tables are reused.

If may be fixable by going back to `v1.7.4`. I am pretty much on my way out the door for a few days, so it may take me a little longer than expected to get a fix ready.

**Comment by klauspost** [comment]
Found the issue. See #173 I will merge it to master and have fuzz tests run before I make a release (probably v1.9.0)

**Comment by klauspost** [comment]
@fproulx-eoscanada v1.9.0 released
