### ISSUE TITLE
Troubleshooting performance problem

### ISSUE THREAD

**Issue by diegobernardes** [klauspost/compress#182]
I'm working on a project that one of the requirements is to process a list of gzip files. They're about 50 MB compressed and 500 MB uncompressed. When I added the uncompressed part using the compress package the performance dropped by half.

At the profiler looks like I'm spending almost all the time at the application doing syscalls.  
![image](https://user-images.githubusercontent.com/14483/68809217-5e30b200-0663-11ea-97c4-28928a6aa70d.png)

And this is my question, if the compress package uses bufio, the rest of the processing is just "number crushing", right? Or I am missing something? I'm just trying to understand why all this time on syscall.

**Comment by klauspost** [comment]
@diegobernardes - Add a `bufio.Buffer`  between your input and the gzip reader, or use pgzip: https://github.com/klauspost/pgzip
