### ISSUE TITLE
Integrate golang/go#11030

### ISSUE THREAD

**Issue by toqueteos** [klauspost/compress#2]
Hi there,

I just found your project, also skimmed over pgzip. Is zlib support somewhat planned or it's just not worth it? After checking zlib's source code it's just 150 lines of extensive use of `compress/flate` and `hash/adler32`.

p.d: Thanks for your work! Having https://github.com/golang/go/issues/11030 resolved in an external library compatible with 1.4 is awesome!

**Comment by klauspost** [comment]
I added zlib. Thanks for the suggestion.

I based the code on 1.4.2, so I actually don't think the patch above is included. However, it seems like it would be trivial to do so.

**Comment by klauspost** [comment]
(changing the title)

**Comment by klauspost** [comment]
Merged, all tests pass.

**Comment by toqueteos** [comment]
Woah, that was amazingly fast! Thank you very much!

**Comment by klauspost** [comment]
Yes, it was mostly changes to Inflate, which I haven't touched.
