### ISSUE TITLE
Support for Go modules

### ISSUE THREAD

**Issue by achille-roussel** [klauspost/compress#208]
Hello!

A pull request was opened against kafka-go to take a dependency on this package to replace the CGO Zstd implementation with the one provided here.

It appears that there are no `go.mod` file in this repository, which means some indirect dependencies get reflected in kafka-go (see https://github.com/segmentio/kafka-go/pull/396/files).

Are there any concerns with adding a `go.mod` file here to list the dependency requirements of `klauspost/compress`?

**Comment by klauspost** [comment]
Yes, there is no need for it. I will remove the dependency.
