### ISSUE TITLE
Get rid of the ebook

### ISSUE THREAD

**Issue by aviau** [klauspost/compress#23]
Hey,

Would you mind getting rid of the ebook? (```testdata/Mark.Twain-Tom.Sawyer.txt```)

I am packaging compress for Debian and I don't think this book is free software ;). Maybe replace it with gibberish?

**Comment by klauspost** [comment]
I would believe it is public domain.

It is [included in the go language itself](https://github.com/golang/go/tree/master/src/compress/testdata).
