### ISSUE TITLE
zstd: Extra encoders and decoders allocated when working with stream APIs

### ISSUE THREAD

**Issue by jpchen-lightstep** [klauspost/compress#235]
It looks like the encoders allocated in Encoder.initialize are only used when EncodeAll is called.  When exclusively using the stream-based API, these encoders appear to be unused.  A similar issue exists with the frame decoders on the decoding side.

Any advice on how to avoid these extra allocations?  I'm working in an environment where we are only using the stream APIs and would like to optimize memory usage.  Thanks!

**Comment by klauspost** [comment]
@jpchen-lightstep Well spotted. Sending in a PR.

**Comment by jpchen-lightstep** [comment]
Thanks so much for the quick turnaround!

Is there a similar issue on the decoding side where the frame decoders created in NewReader are unused when only using the stream-based API?
