### ISSUE TITLE
zstd: Extra decoders allocated when working with stream APIs

### ISSUE THREAD

**Issue by jpchen-lightstep** [klauspost/compress#242]
This is a follow-up to issue #235.  Thank you for the fix to skip creating encoders when using stream APIs.  I believe there's still a similar issue on the decoding side where unused frame decoders are allocated in Decoder.NewReader?

**Comment by klauspost** [comment]
@jpchen-lightstep I don't really see what you are referring to.

**Comment by jpchen-lightstep** [comment]
@klauspost If I'm only using the stream API, I think the decoders allocated [here](https://github.com/klauspost/compress/blob/dcaf1a6516ae48c62a38b776817c3dd19086a1a3/zstd/decoder.go#L94) are not used, right?  (The frame decoders that are used in this scenarios are allocated in [startStreamDecoder](https://github.com/klauspost/compress/blob/dcaf1a6516ae48c62a38b776817c3dd19086a1a3/zstd/decoder.go#L451).)

**Comment by klauspost** [comment]
The frame decoder is not used, but the block decoders are, here: https://github.com/klauspost/compress/blob/dcaf1a6516ae48c62a38b776817c3dd19086a1a3/zstd/decoder.go#L481

We could pull a frame decoder of the channel, not sure it would make much difference. The `frameDec` struct isn't that big. Small decodes should use the `DecodeAll` function anyway.

**Comment by klauspost** [comment]
I think I will keep it as it is. When the encoder is created we don't know how it will be used and the allocation size is extremely small.

**Comment by jpchen-lightstep** [comment]
Sorry I didn't reply earlier.  I agree with closing this for now given that the frame decoders are small.  Thanks!
