### ISSUE TITLE
Do not cache errors obtained from the underlying reader in all the decompressors

### ISSUE THREAD

**Issue by valyala** [klauspost/compress#279]
### The issue

Decompressors currently cache the error returned from the underlying reader. This error shouldn't be cached, since this may break reading data when the underlying reader returns recoverable error such as read timeout.

### The solution

Do not cache errors from underlying readers during data decompression. Note that errors related to data decompression itself may be cached.
It is also worth noting that the error returned from the underlying reader must be propagated to the caller only if zero bytes are read. If at least a single byte read, then the decompressor could make forward progress by decompressing additional data. So the error may be ignored at decompressor level - it will be returned next time when zero bytes are read from the underlying reader.

**Comment by valyala** [comment]
This may lead to issues like https://github.com/VictoriaMetrics/VictoriaMetrics/issues/696 when the caller retries reading data on timeouts.

**Comment by klauspost** [comment]
There is no direct correlation between input and output, so not having a persistent error is not that easy.

I suggest you write a Reader/Writer that handles retrying outside of the compression package. That will enable you to do it selectively and make it transparent. Handling it before the compression should be about the same work as handling it after.
