### ISSUE TITLE
reading https://proxy.golang.org/github.com/klauspost/compress/@v/v1.10.11.zip: 403 Forbidden

### ISSUE THREAD

**Issue by sumanlucky05** [klauspost/compress#283]
I am getting the above error while downloading this package. Is there any proxy that needs to be set. I am having an issue with only this package.

**Comment by klauspost** [comment]
That is an issue with `proxy.golang.org`

See their site https://proxy.golang.org/ - they ask you to file issues here: https://golang.org/issue/new?title=proxy.golang.org
