### ISSUE TITLE
zstd: Should allLitEntropy be set to true in encoderOptions.setDefault()?

### ISSUE THREAD

**Issue by dop251** [klauspost/compress#285]
Hi,

I've noticed worse zstd compression ratios after upgrading to a new version.

Turns out the compression level was not explicitly set which means allLitEntropy remains false, however the value corresponding to the default compression level should be true. Maybe worth looking at.

Many thanks.

**Comment by klauspost** [comment]
@dop251 I will double check. Some tweaks were made since very small blocks spent a lot of time with little gains, but I might have missed something.

Thanks for the report!

**Comment by dop251** [comment]
Just to clarify, I think there is an inconsistency in the API, because the default compression level is `SpeedDefault`, so in theory the following 2 expressions should be equivalent:
```go
zstd.NewWriter(wr)
```
and
```go
zstd.NewWriter(wr, zstd.WithEncoderLevel(zstd.SpeedDefault))
```
however, they are not, because `zstd.WithEncoderLevel(zstd.SpeedDefault)` sets `allLitEntropy` to `true` (https://github.com/klauspost/compress/blob/a2bf5b1ec3aacf98b277bbce76074c193c0cd97e/zstd/encoder_options.go#L214), and `setDefault()` does not (https://github.com/klauspost/compress/blob/a2bf5b1ec3aacf98b277bbce76074c193c0cd97e/zstd/encoder_options.go#L31)

**Comment by klauspost** [comment]
You are 100% correct.
