### ISSUE TITLE
Merge into standard library

### ISSUE THREAD

**Issue by mholt** [klauspost/compress#3]
Good work with these optimizations! Is there a reason that these improvements shouldn't/wouldn't be merged into the standard library?

**Comment by klauspost** [comment]
It is fairly specific to x64 - which IS the main majority I would expect). Without the assembler code, the changes aren't that big, and might be worse on 32 bit systems.

But after a while I might submit it, I would like for it to be field-tested a bit before that.

**Comment by mholt** [comment]
Fair enough. I think the improvements are worth the effort. I'll try to deploy this package in an app and will let you know how it fares. Thanks for sharing!

**Comment by eaigner** [comment]
Nowadays most machines are x64, so I guess the core lib would definitely benefit from it.

**Comment by shishkander** [comment]
For **our** workloads (~2GB executables uploaded with gzipping), your package gives about 2x speed gain in my benchmarks on 64bit Linux.

**Comment by gorakhargosh** [comment]
+1.

Great work!

I'd request you to sent these for code reviews one by one instead
of waiting until all of it is ready. Very large code changes tend to be 
hard to review and require setting time apart just for reviewing.

(Have experienced this first-hand on internal CLs.) 

Thank you. :)

Cheers,
Yesudeep.

**Comment by martingartonft** [comment]
Nice work. I've use this successfully in one of our projects.
It would great to get it into the standard library too.  Let me know if there is anything I can do to help with that somehow.

**Comment by mholt** [comment]
Just reporting back -- been using this in production for several months now with 0 (known) problems.

**Comment by derekperkins** [comment]
We're using this and haven't had any issues. Is it too late for 1.6?

**Comment by klauspost** [comment]
1.6 is closed for new features (and has been for >1 month).

My aim is to submit it at the start of 1.7, so it can live in "tip" for a while.

My aim is to weed out subtle and rare failures like #20, which has gone undetected since the start of the project.

**Comment by klauspost** [comment]
It has begun: https://go-review.googlesource.com/19336

**Comment by mholt** [comment]
@klauspost Very nice! So this was merged and it looks like Go 1.6.1 comes out very soon. Do you know if your contributions will be in that release? Is this repo ahead of those contributions at all? (Looks like a few commits squeezed in here after being merged into golang/go.)

**Comment by nhooyr** [comment]
Have all of these changes been merged into the standard library? Will this package be deprecated?

**Comment by klauspost** [comment]
Some of it has been merged, closing the gap to ~10%. The Go deflate has not been rebalanced, so using "standard" is still ~1.5x faster, but loses ~2% in efficiency.
