### ISSUE TITLE
zstd.Encoder consumes at least 8 MB of memory

### ISSUE THREAD

**Issue by marten-seemann** [klauspost/compress#316]
First of all, thank you for this amazing library! I'm using zstd to compress QUIC log files in [libp2p](https://github.com/libp2p/go-libp2p-quic-transport). Switching from gzip to zstd allowed me to [speed up](https://github.com/libp2p/go-libp2p-quic-transport/pull/190) the compression by roughly 6x (at comparable file sizes).

I'm running into problems regarding the memory consumption of the zstd implementation though. A node can easily have hundreds of active connections, each of them logging through their own `zstd.Encoder`.
As far as I can tell, the reason for this is that a `zstd.Encoder` is initialized with a massive buffer of 8 MB in https://github.com/klauspost/compress/blob/b5cd74455ec97bb16c8a4b3a655eded57ccc4aef/zstd/enc_base.go#L131-L138
This is because `e.maxMatchOff` is 4 MB.

I have to admit that I don't understand a lot of the internals of zstd, so I'm not sure if this is something that can be optimized. Ideally, a `zstd.Encoder` would consume << 1 MB on initialization, and only allocate more memory if and when it's actually needed.

**Comment by klauspost** [comment]
@marten-seemann You can use the [WithWindowSize](https://pkg.go.dev/github.com/klauspost/compress/zstd#WithWindowSize) to adjust the window size of the encoder.
