### ISSUE TITLE
Xz

### ISSUE THREAD

**Issue by 89z** [klauspost/compress#317]
I was wondering if you would consider adding Xz support. The popular Xz repo [1], decodes extremely slowly. I found another Xz that has good speed [2], but it has not been updated in some years. Plus, because of missing license, the documentation is broken [3].

I was thinking you could just copy the code from [2], then users could do:

~~~go
import "github.com/klauspost/compress/xz"
~~~

1. https://github.com/ulikunitz/xz
2. https://github.com/xi2/xz
3. https://pkg.go.dev/github.com/xi2/xz

**Comment by andrewarchi** [comment]
I too would appreciate a Go XZ decompression implementation.

For now, you can create an `io.Reader` that uses the much faster `xz` command in PATH and falls back to ulikunitz/xz, when not available. This snippet is from my [andrewarchi/archive](https://github.com/andrewarchi/archive/blob/3930910aa1f7b1a8e82f02d31c453e0941e79f4e/xz.go) repo. I haven't figured out how to make a corresponding `io.Writer`; the pipes are tricky.

```go
// NewXZReader returns a reader that decompresses XZ data using system
// xz, if in PATH, otherwise falling back to a slower Go implementation.
func NewXZReader(r io.Reader) (io.ReadCloser, error) {
	if _, err := exec.LookPath("xz"); err != nil {
		xr, err := xz.NewReader(r)
		if err != nil {
			return nil, err
		}
		return ioutil.NopCloser(xr), nil
	}

	rpipe, wpipe := io.Pipe()
	var errb bytes.Buffer
	cmd := exec.Command("xz", "--decompress", "--stdout")
	cmd.Stdin = r
	cmd.Stdout = wpipe
	cmd.Stderr = &errb
	go func() {
		err := cmd.Run()
		if err != nil && errb.Len() != 0 {
			err = errors.New(strings.TrimRight(errb.String(), "\r\n"))
		}
		wpipe.CloseWithError(err)
	}()
	return rpipe, nil
}
```

**Comment by 89z** [comment]
@andrewarchi if https://github.com/ulikunitz/xz was the only Go Xz implementation, your idea would be worth considering. But as I noted, another implementation already exists with good speed. Because of that, your suggestion is poor. I would also note that your solution completely fails on Windows.

**Comment by klauspost** [comment]
I still have things I want to add to zstd, mainly concurrent stream compression before I'll move on to something else.

LZMA (used in xz) or brotli are candidates. 

LZMA is good at "ultimate compression", but inherently slow and rarely worth it compared to zstd.

I don't like brotli, since it isn't really good at much, but being a Google project Chrome supports it, so it would be useful...

**Comment by Jacalz** [comment]
I agree with you there.

I don't personally see a lot of usefulness for brotli, but my use case for wanting xz is basically just for backwards comparability. I do see zstd as the next standard in compression, but xz is still widely used. It is especially popular for distribution of source code tarballs on UNIX.

**Comment by Jacalz** [comment]
Why was this closed?

**Comment by 89z** [comment]
@Jacalz some things have changed since I posted the issue:

> [ulikunitz/xz] decodes extremely slowly

this can be mitigated by doing something like this:

~~~
xz.NewReader(bufio.NewReader(something))
~~~

> [xi2/xz] has good speed, but it has not been updated in some years. Plus, because of missing license, the documentation is broken

The above is all still true, but `ulikunitz/xz` with `bufio` is almost as fast as `xi2/xz`, so either option is good.

**Comment by Jacalz** [comment]
I don't think that it necessarily solves this issue for all of our other use cases. I still think there would be a very valid reason for having a good xz implementation here.

**Comment by 89z** [comment]
If you consider other modern options such as Zst, then you quickly realize that Xz is an old crappy format that needs to die. This isn't the 90s, where everyone is on dialup, and all that matters is output size. The bottleneck these days isn't network transfer, and hasn't been for several years. The bottleneck these days is decompress speed. And even in ideal conditions, Xz isn't good, and never was good with that metric. It was made for a different time.

The only reason I care about Xz at all, is because some people are foolishly still using it (the Rust project in my case). Otherwise I would have nothing to do with it. The last thing that I want to do, is anything that will slow the death of Xz, which this issue does. Now that ulikunitz/xz is "good enough", this issue should be closed, and stay closed.

Please don't take any of the above as insult, I only take issue with people continuing to use decades old crap, when better software is available.
