### ISSUE TITLE
Implement semantic versioning

### ISSUE THREAD

**Issue by bluego-joe** [klauspost/compress#355]
The lack of semantic versioning of this package breaks downstream projects when `go get -u all` is run.

For example, v1.12.1 removed the `snappy` package. If semantic versioning were being used this would have been v2.0.0.

This is an issue because downstream projects must now add a `replace` to their `go.mod` file until intermediate dependencies are updated.

**Comment by klauspost** [comment]
@bluego-joe Pin the version. Having to deal with v2 is a much bigger hazzle than to replace an import.

Snappy package has been discouraged for years now.
