### ISSUE TITLE
Test got "invalid input: magic number mismatch"

### ISSUE THREAD

**Issue by jinlianch** [klauspost/compress#377]
go version go1.15.11 darwin/amd64
klauspost v12.2

I wrote a test function to calculate the compress ratio of zstd,  traversed a list of files, and call zstdKlauspostCompressRatio, got this error sometimes, "invalid input: magic number mismatch", but if I do compress the data separately, it runs well.
Failed here : _, err = decoder.WriteTo(nsrcbf)

```
func zstdKlauspostCompressRatio(t *testing.T, src []byte) {
	dst := bytes.NewBuffer(make([]byte, 0, len(src)))
	srcrd := bytes.NewReader(nil)
	nsrcbf := bytes.NewBuffer(make([]byte, 0, len(src)))
	levelOpt := kzstd.WithEncoderLevel(kzstd.EncoderLevelFromZstd(zstd_level))
	encoder, err := kzstd.NewWriter(dst, levelOpt)
	if err != nil {
		t.Fatal(err)
	}
	defer encoder.Close()
	decoder, err := kzstd.NewReader(srcrd)
	if err != nil {
		t.Fatal(err)
	}
	defer decoder.Close()
	_, err = encoder.Write(src)
	if err != nil {
		t.Fatal(err)
	}

	encoder.Close()
	data := dst.Bytes()
	dstl := len(data)
	srcl := len(src)
	t.Logf("zstd_k level: %d org_len: %v com_len: %v ratio: %v\n", zstd_level,
		srcl, dstl, float64(dstl)/float64(srcl))
	srcrd.Reset(data)
	err = decoder.Reset(srcrd)
	if err != nil {
		t.Fatal(err)
	}
	_, err = decoder.WriteTo(nsrcbf)
	if err != nil {
		t.Fatal(err)
	}
	ddst := nsrcbf.Bytes()
	if err := cmp(src, ddst); err != nil {
		t.Fatalf("zstd_k compress failed %v \n", err)
	} else {
		t.Log("zstd_k compress succ\n")
	}
}
```

**Comment by klauspost** [comment]
Looks good on first impression. I should be able to test it tomorrow and tell you what is going on.

**Comment by klauspost** [comment]
Send nil to the first reader. Maybe that helps.

**Comment by jinlianch** [comment]
> Send nil to the first reader. Maybe that helps.

Yes, it work. Thanks.

**Comment by klauspost** [comment]
I will see if I can reproduce the inconsistency. Do note that it will start decoding as soon as it is it constructed, but with an empty buffer there shouldn't be any output.

**Comment by klauspost** [comment]
I reproduced this with a non-racing setup. I expect to send a fix shortly.

**Comment by klauspost** [comment]
@jinlianch The main problem is that `err = decoder.Reset(srcrd)` is unsafe and racy since it is still being used by the decoder. You are modifying the data while it is being read/decompressed.

I added a test that checks if any data/error is unsynchronized, but it doesn't appear there is.
