### ISSUE TITLE
Ability to decode streams compressed with "zstd long=31"

### ISSUE THREAD

**Issue by pushshift** [klauspost/compress#390]
I use very large window sizes when compressing data (up to the maximum of 2 << 31). I noticed that the package has a MaxWindowSize of 2 << 29. 

How would I go about decoding streams compressed with long=31? Was support for larger window sizes purposely left out?

Thanks!

**Comment by pushshift** [comment]
FYI -- I monkey patched the const located in framedec.go and was able to stream in a zstd stream encoded with long=31 without any issue. My recommendation would be to increase MaxWindowSize to the actual maximum allowed by zstandard itself (when using the long flag, this is 2 << 31).

**Comment by pushshift** [comment]
https://github.com/klauspost/compress/pull/392

**Comment by klauspost** [comment]
`2 << 31` is 4GB. Either way, that is just as arbitrary a limit as the current.

I made the maximum configurable and clarified the documentation. See #394

**Comment by pushshift** [comment]
Thank you! That's great. Also, is 2 << 31 4GB? The warning zstd gives looks like:

```
-06-07_00.ndjson.zst : Decoding error (36) : Frame requires too much memory for decoding 
-06-07_00.ndjson.zst : Window size larger than maximum : 2147483648 > 134217728 
-06-07_00.ndjson.zst : Use --long=31 or --memory=2048MB
```

Either way, that appears to be the maximum that can be used for zstd, but I really like the idea of making the window configurable. Awesome project by the way -- really impressive work!

**Comment by klauspost** [comment]
@pushshift `2 << 31` <- you are shifting a 2, making it `1 << 32`.

Thanks for the contribution and the kind words. I have merged the PR.
