### ISSUE TITLE
'invalid compressed data--crc error' when using GzipHandler()

### ISSUE THREAD

**Issue by tony2001** [klauspost/compress#409]
I use gzhttp.GzipHandler() with multiple handlers in one application and *occasionally* (I reproduced it several times already) I get 'invalid compressed data--crc error' when uncompressing the data from the handler.
Can't think of any way my code could've caused it - it looks quite straightforward:
```
            mux := http.NewServeMux()
            mux.Handle("/metrics", gzhttp.GzipHandler(api.NewMetricsHandler(renderer))
            if metricsErr := http.ListenAndServe(metricsPort, mux); metricsErr != nil {
               ...
            } 
```
So the only possible culprit is the GzipHandler itself.
Any idea how to debug it? 
I've saved a broken file just in case, but I know very little about gzip structure, so it looks pretty much like any other gzip file to me.

**Comment by klauspost** [comment]
Could you attach the received data? Maybe inside a zip if it will not otherwise allow it.

**Comment by tony2001** [comment]
[metrics_broken.gz](https://github.com/klauspost/compress/files/6822194/metrics_broken.gz)

**Comment by tony2001** [comment]
JFYI, it looks like it was indeed my fault after all - I tried to reduce memory allocations and was caching buffers that could've been rewritten by other goroutines. 
Weird that race detector didn't catch it and I still don't fully understand how it could've caused "crc error".
In any case, it's not a problem in gziphandler for sure.
