### ISSUE TITLE
Include different LICENSEs in top-level LICENSE file

### ISSUE THREAD

**Issue by stapelberg** [klauspost/compress#417]
The repository itself is licensed under the Go license at the top level (`LICENSE`).

However, there are 2 subdirectories with a different license:

1. `gzhttp/LICENSE` (Apache-2)
2. `s2/cmd/internal/readahead/LICENSE` (BSD 3-clause)

Are these parts of the code intentionally licensed differently?

If yes, could these licenses be added to the top-level `LICENSE` file please?

A common syntax seems to be something along these lines:
```
Files: src/<directory name>/*

<License Text>

------------------

Files: src/<directory name>/*

<License Text>
```

Thank you!

**Comment by klauspost** [comment]
Sure.
