### ISSUE TITLE
Fix go.mod

### ISSUE THREAD

**Issue by 89z** [klauspost/compress#419]
Current `go.mod` looks like this:

https://github.com/klauspost/compress/blob/77932353352e54054c0b7254764c4fab4ea6c51d/go.mod#L1-L5

but it should look like this:

~~~
module github.com/klauspost/compress
go 1.17
require github.com/golang/snappy v0.0.4
~~~

because of this, every single package that uses `klauspost/compress` is now getting an indirect require on the snappy package. I think you can fix it by just deleting that line in the file, and running `go mod tidy`.

**Comment by klauspost** [comment]
It may be because there is only testing reference to snappy.

Maybe it would be possible to move these tests somewhere else and have a separate go.mod for that, so the main package doesn't depend on snappy.

**Comment by klauspost** [comment]
Decided to just include a sparse internal package for it, so the dependency is removed.
