### ISSUE TITLE
References for algorithm in Estimate?

### ISSUE THREAD

**Issue by akshayjshah** [klauspost/compress#423]
Thank you for putting together such an excellent module - it's been useful not just as a faster implementation of some stdlib packages, but as a guide to understanding the algorithms!

Do you happen to have a reference available for the algorithm and constants used in `compress.Estimate`? My math is _very_ rusty, but I think I follow the broad strokes of the algorithm: compressibility is partly the distribution of bytes in the input, and partly how successful a very simple predictive model is. I'm not sure where the constants `0.6`, `0.4`, and `0.9` come from - are they part of some well-known implementation, or did you discover them empirically? Is there a good reference for this particular approach to estimating compressibility? (The best I've found is https://en.wikibooks.org/wiki/Data_Compression/Order/Entropy.)

Thanks for any insight you can offer :)

**Comment by akshayjshah** [comment]
Even after reading some references, I'm having trouble following the details of `Estimate`. I've pushed a commit to my fork with some comments highlighting the bits that I'm not following: https://github.com/klauspost/compress/compare/master...akshayjshah:estimate?expand=1

I realize that you're not here as a private tutor, but I'd appreciate any clarifications you've got the time for. If you'd like, I'm happy to take any explanations, work them into comments in the code, and open a PR to improve the documentation for the next curious person :)

**Comment by klauspost** [comment]
There are no references and as such it was mostly an experiment to pre-classify content before compression. So most values are just handtuned to give a reasonably distributed input and match the input reasonably.

What I found was that it is just faster to actually compress the input, so I didn't end up using it for anything, but left it there if anyone actually did.

**Comment by akshayjshah** [comment]
Got it! Thanks, @klauspost.
