### ISSUE TITLE
when dynamic linking, R15 is clobbered by a global variable access

### ISSUE THREAD

**Issue by efabens** [klauspost/compress#428]
When compiling in plugin mode I am getting the following error
```
> go build -buildmode=plugin plugins/requestlogger/requestlogger.go
```
```
# github.com/klauspost/compress/zstd/internal/xxhash
asm: xxhash_amd64.s:120: when dynamic linking, R15 is clobbered by a global variable access and is used here: 00092 (/Users/efabens/go/pkg/mod/github.com/klauspost/compress@v1.13.5/zstd/internal/xxhash/xxhash_amd64.s:120)        ADDQ    R15, AX
asm: assembly failed
```

**CONTEXT**
The requestlogger.go, uses https://github.com/tozny/utils-go/blob/b17551f08121c0f8be8e660e5004547930380ea3/stream/kakfa.go#L126 which uses https://github.com/Shopify/sarama which in turn uses this lovely library.

I sincerely wish I knew assembly well enough to be able to help resolve this issue but alas that is not a specialty of mine.

**What I have found, that may be useful**
https://groups.google.com/g/golang-codereviews/c/124cVR_LDTo
https://github.com/golang/go/issues/43661

**Comment by efabens** [comment]
Forgot to give versions.

- `go 1.17 darwin/amd64` on macOS 11.4
- `go version go1.17 linux/amd64` docker build in image based on alpine 3.14.2

**Comment by klauspost** [comment]
Fixed by https://github.com/klauspost/compress/pull/430

**Comment by efabens** [comment]
Thank You!
