### ISSUE TITLE
Unable to go get klauspot/compress/zstd

### ISSUE THREAD

**Issue by teresa-recursion** [klauspost/compress#429]
I'm getting a new error when doing a `go build` for a project that has a klauspsost/compresss dependency. 

```
cannot load github.com/klauspost/compress/zstd: github.com/klauspost/compress@v1.13.
1: reading https://proxy.golang.org/github.com/klauspost/compress/@v/v1.13.1.zip: 403 Forbidden 
```

I see that `github.com/klauspost/compress/zstd` exists, so I'm not sure why it's falling back on `https://proxy.golang.org/github.com/klauspost/compress/@v/v1.13.1.zip` and even then, when I navigate to that URL I download the zip successfully (although there is a 302).  

I'm running `go build` in the [golang:latest docker image](https://hub.docker.com/_/golang).

go1.16.5
linux_amd64

Any ideas what could be going on here?

**Comment by klauspost** [comment]
@teresa-recursion Unfortunately I have no idea what is going on.

Maybe upgrade to v1.13.5

I see yo already created an issue: https://github.com/golang/go/issues/48107
