### ISSUE TITLE
Binaries using this as a dep are reported as malware

### ISSUE THREAD

**Issue by Jacalz** [klauspost/compress#440]
I realize that this might sound like a strange issue and it most likely is, but hang with me. I got a report a while back, that my binaries for [wormhole-gui](https://github.com/Jacalz/wormhole-gui) were being flagged as potentially malware (https://github.com/Jacalz/wormhole-gui/issues/21). I initially closed the issue as I just thought it was the usual warning about unsigned binaries, but upon more information surfacing, I really had to dig into the issue a bit more.

Upon further investigation and a lot of compilations of Windows binaries, I eventually reverted the change where I had updated this project (https://github.com/klauspost/compress) from [v1.11.7](https://github.com/klauspost/compress/releases/tag/v1.11.7) to [v1.13.3](https://github.com/klauspost/compress/releases/tag/v1.13.3). Upon reverting that change, my binaries are no longer being flagged as malware on VirusTotal. Strangely, these malware reports (https://www.virustotal.com/gui/file/894dd0794c55f270ed56e2306483f41ee13ce2b2b62feb5ca3cbe5f94b7a0ecc for example) seem to also go away when updating to [v1.13.6](https://github.com/klauspost/compress/releases/tag/v1.13.6).

I am also seeing relatively similar reports for https://github.com/klauspost/compress/releases/download/v1.13.6/s2-Windows_x86_64_1.13.6.zip when running it through VirusTotal: https://www.virustotal.com/gui/file/5ae1c47aa2d9102902279a9df9c1c5e50bf84ba21684f4dd64a4e94c9a8ea338.

My suspection is that there is something with the assembly code that is triggering a false positive with the malware checks. I wanted to inform you so that you are aware and can then perhaps properly digest why this is happening. Thanks.

**Comment by klauspost** [comment]
@Jacalz There is nothing I can really do about it. Crappy virus scanners will be crappy.

**Comment by klauspost** [comment]
Thanks for the heads up, though.
