### ISSUE TITLE
zstd: Encoder emits invalid empty stream

### ISSUE THREAD

**Issue by dsnet** [klauspost/compress#449]
According to the `zstd` command-line tool, an empty sequence is an invalid input:
```
$ zstd --version
*** zstd command line interface 64-bits v1.4.4, by Yann Collet ***
$ echo -n | zstd -d
zstd: /*stdin*\: unexpected end of file
```

However, [the `zstd` Go package currently emits an empty output for an empty input](https://play.golang.org/p/vUn7Hxkyz_d):
```go
var bb bytes.Buffer
zw, err := zstd.NewWriter(&bb)
if err != nil {
	panic(err)
}
if err := zw.Close(); err != nil {
	panic(err)
}
fmt.Printf("%q\n", bb.Bytes()) // prints ""
```

According to the `zstd` command-line tool, the shortest compressed output is the following:
```
$ echo -n | zstd | xxd -p
28b52ffd240001000099e9d851
```

**Comment by klauspost** [comment]
@dsnet Use [WithZeroFrames](https://pkg.go.dev/github.com/klauspost/compress/zstd#WithZeroFrames) option.

There is nothing in the specification that requires 0 length input to be written to output. It is an interpretation by the commandline tool. Of course it allows you to verify that the input hasn't been truncated, but it isn't strictly needed.

**Comment by dsnet** [comment]
> It is an interpretation by the commandline tool

Wouldn't it be reasonable to match the commandline tool for this behavior given that the tool is written by the same author as that zstandard specification itself?
