### ISSUE TITLE
how to check file format from magic numbers

### ISSUE THREAD

**Issue by Thanh-iT-2001** [klauspost/compress#450]
can you check what compression format this code is in??
magic number is
22 4A 00 EF C6 5F 00 00 28 B5 2F FD 63 E7 55 43 0B C6 5E 3D 13 00 53 0C 2B 58 CC 0B C6 08 42 4C

**Comment by klauspost** [comment]
@Thanh-iT-2001 It doesn't match anything I know.

Here are some common ones: https://github.com/minio/minio/blob/069432566fcfac1f1053677cc925ddafd750730a/cmd/untar.go#L61

**Comment by Thanh-iT-2001** [comment]
**I see There are 4 bytes 28 B5 2F FD. I thought it was zst but those 4 bytes are not at the beginning.. is there any method to check it? help me**

**Comment by klauspost** [comment]
@Thanh-iT-2001 It doesn't match anything I know, sorry.
