### ISSUE TITLE
Re-using the same zstandard encoder over several files keeps growing memory

### ISSUE THREAD

**Issue by jherman** [klauspost/compress#457]
I've read through some other cases on here, but I can't seem to figure out what I may be doing wrong. I'm attempting to use the same encoder, but I can literally watch my memory keep growing.  I'll even sleep the thread to see if Go's garbage collection will clear up the memory after 5 minutes, but that doesn't seem to help. I've attempted to call `runtime.GC()` just to see if it reduces any unused memory, but memory doesn't not get released.

I have a sample written here:

https://github.com/jherman/compression-test

Any suggestions on how to reduce memory consumption?

**Comment by klauspost** [comment]
@jherman How much memory are we talking about?

Internal buffers (and other) are kept between uses, to reduce allocations for each run.

**Comment by jherman** [comment]
After the first compression the process memory will jump about 16MB. The pattern seems to indicate it's about half each iteration, so it then adds 8MB, 4MB, 2MB, etc... It eventually plateaus around ~60MB in memory.

Is there a way to reclaim that space from the buffers between uses? Our goal is to reduce the memory footprint as much as possible. Wondering if my only option is to write compression as separate binary instead.

**Comment by klauspost** [comment]
@jherman That are the buffers for the compression window.

If you don't want them, just don't keep the encoder around. The purpose is that future encodes can use them without having to reallocate.

Use [WithWindowSize](https://pkg.go.dev/github.com/klauspost/compress@v1.13.6/zstd#WithWindowSize) to reduce each window (at a compression ratio cost) and use [WithEncoderConcurrency(1)](https://pkg.go.dev/github.com/klauspost/compress@v1.13.6/zstd#WithEncoderConcurrency) to limit to the number of encoders to keep.
