### ISSUE TITLE
please tag and version this project

### ISSUE THREAD

**Issue by aviau** [klauspost/compress#47]
Hello,

Can you please tag and version this project?

I am the Debian Maintainer for compress and versioning would help Debian keep up with development.

**Comment by klauspost** [comment]
Hi!

How would you prefer this to be done? 

All things that are merged to "master" signifies a new "version". Due to the nature of the library there will not be any API breaking changes.

**Comment by aviau** [comment]
Tagging every time you merge new commits in master would work.

In practice, you may merge many things at the same time so one version after a bunch of commits makes sense. 

Would that work for you?

**Comment by klauspost** [comment]
Not sure. Can't you lock to commits, or what is it for?

**Comment by aviau** [comment]
Distributions like Debian and Fedora have scripts that monitor upstream websites like GitHub to keep up with version numbers. Instead of checking your repository manually from time to time for updates, some notification mechanism will tell me that there is a new version of klauspost/compress to package. I maintain a lot of packages and checking manually is not possible. Unfortunately, this infrastructure is not capable of generating version numbers just by checking the master branch.

**Comment by klauspost** [comment]
Ok, thanks! I will manually add version tags from time to time.

**Comment by aviau** [comment]
Thank you! Just close this bug when you create the first that so that I get notified :)

**Comment by klauspost** [comment]
Done. "v1.0" released.
