### ISSUE TITLE
bzip2 support?

### ISSUE THREAD

**Issue by mitar** [klauspost/compress#474]
There is [great library for parallel decompression for bzip2](https://github.com/cosnicolaou/pbzip2) but there is none I could find for parallel compression. Maybe this library could offer it?

**Comment by klauspost** [comment]
@mitar I don't consider bzip2 that useful. Because of that I don't have any plans to implement it.

**Comment by mitar** [comment]
Oh, why you don't find it useful? I am just curious. It supports multiple streams, has better compression than gzip, and it also supports parallel decompression (where gzip does not)?

**Comment by klauspost** [comment]
@mitar Mainly extremely slow decompression, keeps it from being useful. Not sure what you mean by "multiple streams". 

There are more flexible formats out there, zstandard for one is much more flexible and an order of magnitude faster for decompression.

As you can see I contributed to the decompression lib above, but I don't really see any point in spending time on a compression package.
