### ISSUE TITLE
Refactor zstd Decoder

### ISSUE THREAD

**Issue by klauspost** [klauspost/compress#477]
Currently working on refactoring the zstandard decoder. Goals of the refactor:

* Have fully singlethreaded decoding as option #264 
* Simplify data flow.
* Split multithreaded decoding into: (continuing #100)
   * block decoder/splitter
   * literal decoding
   * sequence decoding
   * sequence execution
 * Allow multiple frames to be decoded concurrently.

**Comment by MarkusFreitag** [comment]
Currently the `*zstd.Decoder` has a `Close` method without a return value and so does not fulfill the `io.ReadCloser` interface. Is this something that can be changed during the refactoring?

I'm not sure whether this belongs to this issue, if not I'm happy to create a new own.

**Comment by klauspost** [comment]
@MarkusFreitag No. That would be a breaking change. Use [IOReadCloser](https://pkg.go.dev/github.com/klauspost/compress@v1.14.2/zstd#Decoder.IOReadCloser).

It shouldn't be used like a standard ReadCloser, so I on purpose does not support the interface.
