### ISSUE TITLE
requestedGzip is false when `Accept-Encoding: gzip` is explicitely set on the Request

### ISSUE THREAD

**Issue by wperron** [klauspost/compress#485]
I made a [quick gist](https://gist.github.com/wperron/11ab95a64e2c377a446f3c61e0590314) to demonstrate the issue, when running through a debugger, we can see that because `req.Header.Get("Accept-Encoding")` is not equal to an empty string, then the Transport doesn't set the `requestedGzip` to true and doesn't attempt to decode the response body.

For context on what I'm trying to do: I have this server that acts as a proxy, it takes in requests, forwards them to a downstream server (along with the initial request headers) and inspects the JSON payload before sending the response back. I added the `GzipHandler` to my server handler to re-compress the response before sending to the client, that works well, now I was expecting to simply plug in the `gzhttp.Transport` on my client and have it work out of the box but it cause the JSON unmarshaling to error out.

I can see why that's the case (if the client explicitely requests gzip encoding, it probably expects gzipped content, not the uncompressed) but that's forcing me to overwrite the request headers to make sure the gzip Transport is decompressing the response.

**Comment by klauspost** [comment]
@wperron It assumes that when you set the `"Accept-Encoding"`, you are dealing with it yourself, ie. handling decompression.

That is also similar to how `http.DefaultTransport` behaves.

**Comment by wperron** [comment]
> @wperron It assumes that when you set the `"Accept-Encoding"`, you are dealing with it yourself, ie. handling decompression.
> 
> That is also similar to how `http.DefaultTransport` behaves.

Right, that's what I figured too. Thing is, I'm not setting it myself, I'm receiving the header from an incoming request and copying it over to an outgoing request. I understand the current behavior, I'm wondering if there's anything we can do here to make my use case simple to handle with the `gzhttp.Transport`?

**Comment by klauspost** [comment]
@wperron Guess it depends on whether you want it to be streaming or you want requests fully in memory.  What you propose seems to be fully in-memory, which of course is risky.

If you just want to "listen in" on the data, but leave it as-is and decompress the data alongside forwarding it. Then you just need to decompress the data when read and keep the code as-is.

0. Forward requests.
1. Read response into `var resp []byte`
2. Inspect "Content-Encoding" on response. If `gzip` do a `json.NewDecoder(gzip.NewReader(bytes.NewBuffer(resp)))`, if not just `json.NewDecoder(bytes.NewBuffer(resp))`.
3. Decode the JSON, do your stuff.
4. If ok, transfer headers and write original response.

If you want to always request gzip upstream and optionally recompress you can:

Decouple the "Accept-Encoding" from the incoming request, so you just delete the header, and leave it to the transport wrapper to add it on the outgoing request.

Your server can then recompress when returning the data if upstream requested it with the `gzhttp.GzipHandler` wrapper.

**Comment by wperron** [comment]
> Decouple the "Accept-Encoding" from the incoming request, so you just delete the header, and leave it to the transport wrapper to add it on the outgoing request.
> 
> Your server can then recompress when returning the data if upstream requested it with the gzhttp.GzipHandler wrapper.

That's my current workaround 😅 It works alright but I don't like that if the client requested `Accept-encoding: gzip` I'm unsetting the header, so it can be re-set later on.

> Guess it depends on whether you want it to be streaming or you want requests fully in memory. What you propose seems to be fully in-memory, which of course is risky.

Yeah that's what I'm looking for, I know it's not ideal, but I need to load the response in-memory, uncompressed, so I can tweak some things.

I guess what I'm looking for is a `Transport` that passes through the provided headers, and checks the response headers to decompressed if necessary, so that the response is always decompressed.

Looking more closely at the available APIs I'm sure I can write a custom `Transport` for my purposes, if you're open to having it included in `gzhttp` I can open a PR for it.

**Comment by klauspost** [comment]
Ah, you want to modify the response.

>  I don't like that if the client requested Accept-encoding: gzip I'm unsetting the header, so it can be re-set later on.

TBH that seems like a reasonable thing to do all things considered. I don't really see any problem with that. Clients may set `Accept-encoding`  you can't support, so you might as well just remove it from the request entirely.

**Comment by wperron** [comment]
What I don't like about it is that unless someone is familiar with `gzhttp` it's not obvious what's happening and _why_ the header is being cleared 🤷 I guess my use-case is pretty specific, I don't really have to worry about other compression algos, I'll just implement a Transport of my own then. Thanks for your time 🙂

**Comment by klauspost** [comment]
@wperron I think a short comment can explain that. Basically it is just so you can control upstream compression independent of downstream compression.
