### ISSUE TITLE
The compiled binary contains lot of test data

### ISSUE THREAD

**Issue by ahmad-kemsan** [klauspost/compress#497]
Issue description

On static analysis of the binary, generated after compiling our go fiber app we found out a lot of text and links in the final binary, which turned out to be test data in the package.

Please check this issue:

https://github.com/gofiber/fiber/issues/1782

**Comment by klauspost** [comment]
This is the [brotli dictionary](https://github.com/nishemon/get-brotli-dictionary). From github.com/andybalholm/brotli

Seems like it has text from common benchmarks. Cheaters.
