### ISSUE TITLE
flate: regression on efficiency for very short strings

### ISSUE THREAD

**Issue by dsnet** [klauspost/compress#50]
Using: 9d711f4445beb7f6488148ce04e3b4dc6e72242d

Example link: https://play.golang.org/p/3N7YRHAmGO

When compressing very short strings, the KP version of flate outputs strings larger than what the standard library did, which itself outputted strings larger than what zlib did.

Compressing the string "a" on level 6, outputs the following:

```
zlib: 4b0400
std:  4a04040000ffff
kp:   04c08100000000009056ff13180000ffff
```

Where `zlib` is the C library, `std` is the Go1.6 standard library, and `kp` is your library. It seems that the KP version uses a dynamic block, rather than a fixed block. If we address this change, we may want to avoid the [final, last, empty block] we currently emit (the 0x0000ffff bytes at the end). That will allow us to produce shorter outputs (like what zlib can produce).

Avoiding the [final, last, empty block] will be beneficial to https://go-review.googlesource.com/#/c/21290/

**Comment by klauspost** [comment]
Correct. "writeBlockDynamic" should check if the size is bigger than "store". 

About the additional block for EOF I have noticed it. I was rather going to remove all the EOF stuff from the bit writer. However, adding an EOF boolean to the compressor could also work.

**Comment by klauspost** [comment]
Backported from Go changes.
