### ISSUE TITLE
Potential nil pointer deference

### ISSUE THREAD

**Issue by saracen** [klauspost/compress#508]
@klauspost After upgrading fastzip to v1.14.4, a user of GItLab-Runner has submitted this report:

```
panic: runtime error: invalid memory address or nil pointer dereference
[signal 0xc0000005 code=0x0 addr=0x0 pc=0xa14ee0]
goroutine 105 [running]:
github.com/klauspost/compress/flate.offsetCode(...)
	/go/pkg/mod/github.com/klauspost/compress@v1.14.4/flate/token.go:373
github.com/klauspost/compress/flate.(*tokens).AddMatchLong(0xc000ba800e, 0xba8000, 0xc0)
	/go/pkg/mod/github.com/klauspost/compress@v1.14.4/flate/token.go:291 +0x20
github.com/klauspost/compress/flate.(*fastEncL5).Encode(0xc000890000, 0xc000b66088, {0xc0006ac000, 0xffff, 0x800000})
	/go/pkg/mod/github.com/klauspost/compress@v1.14.4/flate/level5.go:227 +0xc65
github.com/klauspost/compress/flate.(*compressor).storeFast(0xc000b66000)
	/go/pkg/mod/github.com/klauspost/compress@v1.14.4/flate/deflate.go:679 +0x17d
github.com/klauspost/compress/flate.(*compressor).write(0xc000b66000, {0xc0006be000, 0x8000, 0x2cc9a0})
	/go/pkg/mod/github.com/klauspost/compress@v1.14.4/flate/deflate.go:704 +0x98
github.com/klauspost/compress/flate.(*Writer).Write(0xc000579ab8, {0xc0006be000, 0x2d629e, 0xc000248a00})
	/go/pkg/mod/github.com/klauspost/compress@v1.14.4/flate/deflate.go:865 +0x25
io.(*multiWriter).Write(0xc0006be000, {0xc0006be000, 0x8000, 0x8000})
	/usr/local/go/src/io/multi.go:60 +0x86
bufio.(*Reader).writeBuf(0xc00018a420, {0xf55a40, 0xc000168030})
	/usr/local/go/src/bufio/bufio.go:542 +0x64
bufio.(*Reader).WriteTo(0xc00018a420, {0xf55a40, 0xc000168030})
	/usr/local/go/src/bufio/bufio.go:523 +0x12d
io.copyBuffer({0xf55a40, 0xc000168030}, {0xf53320, 0xc00018a420}, {0x0, 0x0, 0x0})
	/usr/local/go/src/io/io.go:405 +0x16e
io.Copy(...)
	/usr/local/go/src/io/io.go:382
github.com/saracen/fastzip.(*Archiver).compressFile(0xc000638000, {0xf6dfd8, 0xc000406080}, 0xc00014c018, {0xf7a370, 0xc000210b60}, 0xc000b263b8, 0xc0007063c0)
	/go/pkg/mod/github.com/saracen/fastzip@v0.1.8/archiver.go:270 +0x2de
github.com/saracen/fastzip.(*Archiver).createFile(0x0, {0xf6dfd8, 0xc000406080}, {0xc00036a100, 0x0}, {0xf7a370, 0xc000210b60}, 0x64006c00690075, 0x720067005c0073)
	/go/pkg/mod/github.com/saracen/fastzip@v0.1.8/archiver.go:244 +0x10e
github.com/saracen/fastzip.(*Archiver).Archive.func2()
	/go/pkg/mod/github.com/saracen/fastzip@v0.1.8/archiver.go:175 +0xfe
golang.org/x/sync/errgroup.(*Group).Go.func1()
	/go/pkg/mod/golang.org/x/sync@v0.0.0-20210220032951-036812b2e83c/errgroup/errgroup.go:57 +0x67
created by golang.org/x/sync/errgroup.(*Group).Go
	/go/pkg/mod/golang.org/x/sync@v0.0.0-20210220032951-036812b2e83c/errgroup/errgroup.go:54 +0x92
```

https://gitlab.com/gitlab-org/gitlab-runner/-/issues/28903#note_857128578

This might be entirely my fault with how I'm calling your library from `fastzip`, but not much has changed for fastzip. I think Runner was previously using `compress` `v1.11.6`.

Is there anything obvious to you as to what might be the problem?

**Comment by klauspost** [comment]
Thanks! I will investigate!

**Comment by klauspost** [comment]
@saracen This is strange.

The [referenced code](https://github.com/klauspost/compress/blob/v1.14.4/flate/token.go#L373) is impossible to crash.

The `AddMatchLong(0xc000ba800e, 0xba8000, 0xc0)` parameters also looks suspicious. A match length of `0xba8000` is as far as I can tell impossible. This alone is not enough to make it crash.

I could however be reading the stack trace wrong (or it could be wrong) and `0xba8000` is the offset, and the crash is really in line 375.

I can only think of concurrent use of a single Writer. That would cause an impossible offset.

**Comment by klauspost** [comment]
My guess is that [`func (fw *flateWriter) Close() error`](https://github.com/saracen/fastzip/blob/main/register.go#L89) gets called twice (or more), so you get the same writer several times in the pool.

**Comment by saracen** [comment]
Very strange indeed.

I'm not sure it's possible I'm calling `Close()` multiple times. This is the only location for getting the writer from the pool and closing it (placing it back): https://github.com/saracen/fastzip/blob/main/archiver.go#L261-L271

I'll continue digging though. Thanks for your help

**Comment by klauspost** [comment]
@saracen I suspect running with tests with `-race` could give a hint.

**Comment by klauspost** [comment]
Looked through the code (in fastzip), and I cannot find anything wrong. I will continue the investigation tomorrow.

The trace definitely looks wonky.

```
	if off < uint32(len(offsetCodes)) {
->>		return offsetCodes[uint8(off)]
	}
```

`offsetCodes` is a 256 sized array, so `uint8(off)` literally cannot crash. and definitely not with `invalid memory address or nil pointer dereference`. Even crashing in line 275 would cause an out-of-bounds and not invalid memory address.

There is literally no pointers in the piece of code.

**Comment by klauspost** [comment]
@saracen I will need something closer to a reproducer.

I suggest you protect your flateWriter from double closing. Even if it may not be the issue here, it is good practice for `io.Closer`.

```
type flateWriter struct {
	pool *sync.Pool
	flater
	closed bool
}

func (fw *flateWriter) Reset(w io.Writer) {
	fw.closed = false
	fw.flater.Reset(w)
}

func (fw *flateWriter) Close() error {
	if fw.closed {
		return nil
	}
	fw.closed = true
	err := fw.flater.Close()
	fw.pool.Put(fw)
	return err
}
```

**Comment by saracen** [comment]
@klauspost Another failure, outside either of our libraries, was reported by the same user. I don't know what's happening, but it's likely unrelated to anything we're doing.

Thank you for taking time to look into this.

**Comment by klauspost** [comment]
@saracen Did you manage to find the root cause?

**Comment by saracen** [comment]
> @saracen Did you manage to find the root cause?

We have not, but there's additional logs from the user here: https://gitlab.com/gitlab-org/gitlab-runner/-/issues/28903#note_861833488

Crashes appear to be happening at random points and in equally impossible situations.
