### ISSUE TITLE
s2: index speedup

### ISSUE THREAD

**Issue by SaveTheRbtz** [klauspost/compress#554]
Currently index `Find` operations are using linear search, which are simple but quite slow: https://github.com/klauspost/compress/blob/458f43587a830eaa9948e7dc3c0015e217e2576f/s2/index.go#L103-L109.

What do you think about replacing them with either:
* binary search through sort.Search
* btree-based index through https://github.com/google/btree

**Comment by klauspost** [comment]
@SaveTheRbtz Indexes are limited to 65535 entries, so a linear search will never really be that expensive.

Sorted search is faster at ~200 entries, so I will add that.

**Comment by SaveTheRbtz** [comment]
Wow, that was fast!! And here I thought about starting to implement it, lol =)))
