### ISSUE TITLE
`DecodeAll` without checks

### ISSUE THREAD

**Issue by WojciechMula** [klauspost/compress#556]
Background: we may decode the same compressed data several times. Although it's possible the data is broken, then in such a case we won't try to decode it again.

I'm wondering if it would be possible to introduce a variant of decoding, where all sanity checks are not performed (like: if literals are big enough, if match length is within a range, and so on, so forth),

A client code would use it like this:

```go
for i := range inputs {
  // 
  if firstDecode(inputs[i]) {
    decoded, err := decoder.DecodeAll(inputs[i], nil)
    if err {
      ...
    }
  } else {
    decoded := decoder.DecodeAllValid(inputs[i])
  }
}
```

**Comment by klauspost** [comment]
(afk - on mobile, so short answer)

I honestly don't think there will be much difference. Branches are predictable and there aren't really that many checks. 

The important part is allocations, which go away on the second uses. 

I don't really want potentially crashing code to be available. So a "probably no". Maybe if enabled by a build tag.

**Comment by WojciechMula** [comment]
Thank you for the answer. I fully understand you don't want an unsafe code.

**Comment by WojciechMula** [comment]
I have just checked the version without checks --- no significant changes were noticed in benchmarks. The biggest speedup is 1.05x, and some quite significant regressions
