### ISSUE TITLE
how to compress folder?

### ISSUE THREAD

**Issue by jiangjiangjiangjiangjiangjiangjiang** [klauspost/compress#557]
looking forward to a reply

**Comment by Jacalz** [comment]
You can't compress a directory directly but it can be done by creating an archive and then compressing that (for zip, the compression is usually done as part of the archiving process).

Zip: http://stackoverflow.com/questions/37869793/ddg#4923332
Tar: http://stackoverflow.com/questions/39646584/ddg#39647084

**Comment by klauspost** [comment]
Correct, also check [archiver](https://github.com/mholt/archiver).

**Comment by pratikbin** [comment]
Is directory compression possible without tar? zstd cli seems supported 

https://github.com/facebook/zstd?tab=readme-ov-file#dictionary-compression-how-to

**Comment by klauspost** [comment]
@pratikbin dictionary != directory.
