### ISSUE TITLE
zstd: explicitly disable checksum checking

### ISSUE THREAD

**Issue by WojciechMula** [klauspost/compress#571]
This is follow up of #556. In short: we're decompressing the same files over and over. We measured that checksumming takes ~15% of decompression time. We want to conditionally perform checksumming (likely: for the first time).

Would it be possible to add an option to the decoder, like `WithChecksum(false)`?

**Comment by klauspost** [comment]
Yes, sounds reasonable. I would rather have it be `IgnoreChecksum(true)`, but that is a detail.

**Comment by WojciechMula** [comment]
Great! I will prepare a PR for this.
