### ISSUE TITLE
Incompatible seek function of the s2.ReadSeeker if 'whence' is using 'io.SeekEnd'

### ISSUE THREAD

**Issue by jlnieh** [klauspost/compress#574]
Incompatible behavior to use the Seek function of the **s2.ReadSeeker** with s2 Index when using `whence=io.SeekEnd`

- Version: v1.15.2
- Issue description:
  - `filesize, err = rs.Seek(0, io.SeekEnd)`,  expect to get the uncompressed file size, but currently return 0
  - `pos, err = rs.Seek(-10, io.SeekEnd)`, expect to get position at last 10-bytes from end of uncompressed file, but currently return 10

**Comment by klauspost** [comment]
Thanks for the report! Added a fix I will merge shortly.
