### ISSUE TITLE
Too small BlockSizeMax of compress/huff0 to make users cannot import a large zstd dictionary.

### ISSUE THREAD

**Issue by lrita** [klauspost/compress#585]
https://github.com/klauspost/compress/blob/d507a956c12080b811adf71454d2173912efdc91/huff0/huff0.go#L26-L27

https://github.com/facebook/zstd/blob/dev/programs/zstd.1.md

due to the limit of BlockSizeMax is 128kb and the zstd program can generate a given size dictionary by user input `--maxdict=#`.

**Comment by klauspost** [comment]
@lrita Could you explain the problem? These two things aren't related. Could you post a reproducer of the issue?

**Comment by lrita** [comment]
https://github.com/klauspost/compress/blob/d507a956c12080b811adf71454d2173912efdc91/zstd/encoder_options.go#L308-L317

will return [ErrTooBig](https://github.com/klauspost/compress/blob/master/huff0/huff0.go#L38) when the dictionary is large than the 128kb.

**Comment by klauspost** [comment]
@lrita Ah, ok. Now I see. Should be a rather easy fix. Thanks for the report!
