### ISSUE TITLE
flate: remove compressor.hash field

### ISSUE THREAD

**Issue by Jacalz** [klauspost/compress#589]
I found the commit https://github.com/golang/go/commit/949b3e9880bbce0740d1af327b91a0040fe2e12b recently landing for Go 1.19. From what I can tell from the code here in this project, most of the code that is removed in that commit is already present here. Would it be possible to apply something similar in this project?

**Comment by klauspost** [comment]
@Jacalz I doubt it will make much of a difference, but it is also cannot hurt.

**Comment by Jacalz** [comment]
It looks like https://github.com/golang/go/commit/c25c37137db98323510752f53e93128809a8767c landet after the commit mentioned above. I don't know if it is applicable here and if it makes a difference.

**Comment by klauspost** [comment]
@Jacalz That is totally BS. The ONLY relevant difference in the ENCODER is

```
Encode/Digits/Speed/1e5-4          1.65ms ± 2%     1.70ms ± 4%   +2.77%  (p=0.003 n=8+10)
Encode/Newton/Default/1e6-4        58.0ms ± 2%     57.0ms ± 1%   -1.59%  (p=0.001 n=9+9)
```

The rest is DECODER differences, completely unaffected by this change.

**Comment by Jacalz** [comment]
Yeah, I suspected as much. All those upstream commits as of late seem to make almost no changes and report massive speedups. Something is wonky.

**Comment by klauspost** [comment]
Yeah, not bothering with this one. Maybe next time I'm around that code, if it is there.

**Comment by Jacalz** [comment]
Have you reached any conclusion on the open PR?
