### ISSUE TITLE
can't go get this package

### ISSUE THREAD

**Issue by quochungndvt** [klauspost/compress#59]
Hi guy
after i reinstalled go revel, i got this error 
go get github.com/revel/revel
# cd e:\go\datafirst\src\github.com\klauspost\compress; git pull --ff-only
fatal: Not a git repository (or any of the parent directories): .git
package github.com/klauspost/compress/gzip: exit status 128
package github.com/klauspost/compress/zlib: cannot find package "github.com/klauspost/compress/zlib" in any of:
        E:\go1.6\src\github.com\klauspost\compress\zlib (from $GOROOT)
        e:\go\datafirst\src\github.com\klauspost\compress\zlib (from $GOPATH)
        e:\go\gopath\src\github.com\klauspost\compress\zlib
can u check for me
thanks guy

**Comment by klauspost** [comment]
delete the "e:\go\datafirst\src\github.com\klauspost" directory. Use `go get github.com/klauspost/compress/...`

**Comment by quochungndvt** [comment]
thanks guy (y)
