### ISSUE TITLE
Help me

### ISSUE THREAD

**Issue by wuanVN0704** [klauspost/compress#626]
Can you decompress this file? @klauspost
Link file: https://drive.google.com/file/d/1jwlABNJbsPcSR1uUyrhsJCmpScTDeOYx/view?usp=drivesdk

**Comment by klauspost** [comment]
Sorry, without more information I cannot help you.

There is no signature or anything to help identify the format.

**Comment by wuanVN0704** [comment]
Thank you for your quick response, I will try to figure it out if you know
can give me feedback

Vào 11:17 CH, Th 2, 13 thg 6, 2022 Klaus Post ***@***.***> đã
viết:
