### ISSUE TITLE
zstd: WithDecoderMaxMemory does not appear to work

### ISSUE THREAD

**Issue by dsnet** [klauspost/compress#648]
Consider the [following example](https://go.dev/play/p/YF7r4b9i6kv):
```go
enc := E1(zstd.NewWriter(nil))
b := enc.EncodeAll(nil, bytes.Repeat([]byte("hello"), 1<<20))

dec := E1(zstd.NewReader(nil, zstd.WithDecoderMaxMemory(1<<10)))
out, err := dec.DecodeAll(nil, b)
fmt.Println(len(out), err)
```
this currently prints:
```
5242880 <nil>
```
I expect it to print something like:
```
1024 decompressed size exceeds configured limit
```

The documented behavior of `WithDecoderMaxMemory` says:
> WithDecoderMaxMemory allows to set a **maximum decoded size for in-memory non-streaming operations** or maximum window size for streaming operations. This can be used to control memory usage of potentially hostile content. Maximum is 1 << 63 bytes. Default is 64GiB.

Thus, setting it to 1 KiB should cause `Decoder.DecodeAll` to error on inputs that decompress to something larger than 1 KiB. However, that is not the observed behavior.

**Comment by klauspost** [comment]
@nigeltao You swapped input/output parameters:

```
func TestDecoderMaxSize(t *testing.T) {
	enc, _ := zstd.NewWriter(nil)
	b := enc.EncodeAll(bytes.Repeat([]byte("hello"), 1<<20), nil)

	dec, _ := zstd.NewReader(nil, zstd.WithDecoderMaxMemory(1<<10))
	out, err := dec.DecodeAll(b, nil)
	fmt.Println(len(out), err)
}

=== RUN   TestDecoderMaxSize
0 decompressed size exceeds configured limit
```

**Comment by dsnet** [comment]
Eek! Thanks for the quick response.

I've gotten these two mixed up so many times. I wonder if the method should be renamed as `Encoder.AppendEncoded` and `Decoder.AppendDecoded` and have the argument order swapped to match all append-like APIs.

**Comment by klauspost** [comment]
@dsnet As you may be able to see I am very conservative about API changes. But yeah, if we ever do a v2.

**Comment by nigeltao** [comment]
> @nigeltao You swapped input/output parameters:

Speaking of swapping things, I presume you meant @dsnet. :-)

**Comment by klauspost** [comment]
@nigeltao 😆 Must be a hash-collision in my brain! Hope you are doing well - sorry for pinging you.
