### ISSUE TITLE
Shouldn't zstd decoder Close() method return an error?

### ISSUE THREAD

**Issue by mpenkov** [klauspost/compress#650]
https://github.com/klauspost/compress/blob/5a3a4a965cc6dc28df4962646ef8fba7354cc12e/zstd/decoder.go#L586

That would make it compatible with the io.ReadCloser interface.

Just a suggestion :)

**Comment by klauspost** [comment]
It should not be used in the same way. Use [IOReadCloser](https://pkg.go.dev/github.com/klauspost/compress/zstd#Decoder.IOReadCloser) to get a compatible version.
