### ISSUE TITLE
error: package "encoding/binary" without types was imported

### ISSUE THREAD

**Issue by vigneshraman** [klauspost/compress#661]
When building `golang-github-klauspost-compress` from debian bookworm with `golang-1.18` the below error is seen,
```
src/github.com/klauspost/compress/zstd/blockdec.go
stringer: internal error: package "encoding/binary" without types was imported from "github.com/klauspost/compress/zstd"
```

**Comment by klauspost** [comment]
Seems like a 'stringer' problem. You/they are welcome to send a PR if there is anything I can do on my side.
