### ISSUE TITLE
Memory Usage Explosion by zstd

### ISSUE THREAD

**Issue by manishrjain** [klauspost/compress#665]
Hey @klauspost ,

I just switched to using zstd for compression for Outserv boot (/ Dgraph bulk) loader. My map phase produces ~9000 files, which are read concurrently by the reduce phase.

I was using snappy before, and it was working just fine. When I try to read this via zstd, my memory usage just blows up (using 90 GiB).

```
$ go tool pprof localhost:8080/debug/pprof/heap
Fetching profile over HTTP from http://localhost:8080/debug/pprof/heap
Saved profile in /home/out/pprof/pprof.outserv.alloc_objects.alloc_space.inuse_objects.inuse_space.002.pb.gz
File: outserv
Build ID: a3c11775491cc183708fed08da7df4027c01b3cc
Type: inuse_space
Time: Sep 19, 2022 at 10:31pm (UTC)
Entering interactive mode (type "help" for commands, "o" for options)
(pprof) top
Showing nodes accounting for 96.96GB, 98.95% of 97.99GB total
Dropped 145 nodes (cum <= 0.49GB)
Showing top 10 nodes out of 12
      flat  flat%   sum%        cum   cum%
   86.97GB 88.76% 88.76%    86.97GB 88.76%  github.com/klauspost/compress/zstd.(*history).ensureBlock (inline)
    8.71GB  8.89% 97.65%     8.71GB  8.89%  bufio.NewReaderSize (inline)
    1.19GB  1.21% 98.86%     1.19GB  1.21%  github.com/klauspost/compress/zstd.(*blockDec).reset
    0.09GB 0.092% 98.95%    97.27GB 99.27%  github.com/outcaste-io/outserv/outserv/cmd/boot.(*reducer).run.func1
         0     0% 98.95%    88.46GB 90.28%  bufio.(*Reader).Read
         0     0% 98.95%    88.46GB 90.28%  github.com/klauspost/compress/zstd.(*Decoder).Read
         0     0% 98.95%    88.46GB 90.28%  github.com/klauspost/compress/zstd.(*Decoder).nextBlock
         0     0% 98.95%    88.46GB 90.28%  github.com/klauspost/compress/zstd.(*Decoder).nextBlockSync
         0     0% 98.95%     1.19GB  1.21%  github.com/klauspost/compress/zstd.(*frameDec).next
         0     0% 98.95%    97.18GB 99.17%  github.com/outcaste-io/outserv/outserv/cmd/boot.newMapIterator

(pprof) list ensureBlock
Total: 97.99GB
ROUTINE ======================== github.com/klauspost/compress/zstd.(*history).ensureBlock in /home/out/go/pkg/mod/github.com/klauspost/compress@v1.15.10/zstd/history.go
   86.97GB    86.97GB (flat, cum) 88.76% of Total
         .          .     96:}
         .          .     97:
         .          .     98:// ensureBlock will ensure there is space for at least one block...
         .          .     99:func (h *history) ensureBlock() {
         .          .    100:	if cap(h.b) < h.allocFrameBuffer {
   86.97GB    86.97GB    101:		h.b = make([]byte, 0, h.allocFrameBuffer)
         .          .    102:		return
         .          .    103:	}
         .          .    104:
         .          .    105:	avail := cap(h.b) - len(h.b)
         .          .    106:	if avail >= h.windowSize || avail > maxCompressedBlockSize {

```

I'm opening my reader like so:

`dec, err := zstd.NewReader(fd, zstd.WithDecoderConcurrency(1), zstd.WithDecoderLowmem(true))`

So, trying my best to decrease memory usage. Suggestions?

P.S. Tangential, but perhaps consider using jemalloc for such big allocations instead of Go memory.

**Comment by klauspost** [comment]
1) Limit your concurrency. You don't have 9000 cores anyway.
2) Allocate a limited number of Readers. Reuse them using Reset.

Decompressing takes memory. Decompressing 9000x takes huge amount of memory.

**Comment by klauspost** [comment]
Alternatively content must be [encoded with a very small window](https://pkg.go.dev/github.com/klauspost/compress/zstd#WithWindowSize), but that requires you to be in control of the encoding as well.

You can enforce a [max decoder window](https://pkg.go.dev/github.com/klauspost/compress/zstd#WithDecoderMaxWindow), but it will of course fail decoding if that cannot be satisfied.

**Comment by manishrjain** [comment]
I switched to using https://github.com/DataDog/zstd, and it works fine. So, the memory issue is specific to this implementation of zstd.

In the reduce step, the loader has to read through all the map files because each file has sorted data. So, it's sort of like 9000 streams that the reducer has to read to achieve global sorting. With datadog zstd, each stream takes around 1 MiB, so the whole thing can still easily fit in memory.
