### ISSUE TITLE
zstd decoder not re-using memory effectively between Reset() and Read()

### ISSUE THREAD

**Issue by bboreham** [klauspost/compress#666]
I've been stepping through [some decompression code](https://github.com/grafana/loki/blob/93de7a7061f4ada4213874247668ae66480e6695/pkg/chunkenc/memchunk.go) to try to figure out why zstd memory use is much higher than other compression types.

I see that `Reset()` uses the buffer `d.current.b`:
https://github.com/klauspost/compress/blob/697e50752b5ffdc991982a373e20e8093ec7c75a/zstd/decoder.go#L198

Then in my case `DecodeAll` runs and the buffer grows to ~300KB.

Each time `Read()` is called, it advances the start of the buffer:
https://github.com/klauspost/compress/blob/697e50752b5ffdc991982a373e20e8093ec7c75a/zstd/decoder.go#L135

After we read the whole thing, `b` is still pointing into a 300KB buffer, but towards the end.
When we re-use the Decoder, this buffer has len zero and cap ~35KB.  Because 300KB is needed, a new block is allocated.

Could we have the Decoder hold a reference to the beginning of the buffer, so the whole size can be re-used?

Apologies if I'm mis-reading this.

**Comment by bboreham** [comment]
It's not doing exactly the same as my case, but I think `BenchmarkDecoder_DecoderSmall` is a fair illustration:
```
BenchmarkDecoder_DecoderSmall/kppkn.gtb.zst-4                178          10176051 ns/op         144.90 MB/s     4872625 B/op         61 allocs/op
BenchmarkDecoder_DecoderSmall/geo.protodata.zst-4            648           2767123 ns/op         342.85 MB/s     3110672 B/op         35 allocs/op
BenchmarkDecoder_DecoderSmall/plrabn12.txt.zst-4              78          19421308 ns/op         198.49 MB/s    12835731 B/op        113 allocs/op
BenchmarkDecoder_DecoderSmall/lcet10.txt.zst-4               103          11378717 ns/op         300.04 MB/s    11309187 B/op        112 allocs/op
BenchmarkDecoder_DecoderSmall/asyoulik.txt.zst-4             385           4217998 ns/op         237.42 MB/s     3286064 B/op         35 allocs/op
BenchmarkDecoder_DecoderSmall/alice29.txt.zst-4              238           4390828 ns/op         277.10 MB/s     4000791 B/op         64 allocs/op
BenchmarkDecoder_DecoderSmall/html_x_4.zst-4                 231           5616465 ns/op         583.43 MB/s    10776598 B/op         42 allocs/op
BenchmarkDecoder_DecoderSmall/paper-100k.pdf.zst-4          5319           1187369 ns/op         689.93 MB/s     2689064 B/op         30 allocs/op
BenchmarkDecoder_DecoderSmall/fireworks.jpeg.zst-4          1124           1954033 ns/op         503.95 MB/s     3232699 B/op          5 allocs/op
BenchmarkDecoder_DecoderSmall/urls.10K.zst-4                  75          16159240 ns/op         347.58 MB/s    18710788 B/op        164 allocs/op
```

It's calling `Reset()`; the Bytes/op should be close to zero.

**Comment by klauspost** [comment]
You are correct. This is a regression from #649 (and a smaller one from #598)
