### ISSUE TITLE
"illegal combination" error when used in gomobile bind

### ISSUE THREAD

**Issue by ICU2020** [klauspost/compress#681]
I build my android lib with:

gomobile bind -target=android/arm64 -tags='headless' -o=$(my_android_lib) -ldflags="-w -X -s" $(my_dir)

and found the error below:

//# github.com/klauspost/compress/zstd/internal/xxhash
asm: illegal combination: 00072 (<unknown line number>)	PCALIGN	$16 ABCON0 NONE NONE NONE, 4 0
asm: illegal combination: 00072 (<unknown line number>)	PCALIGN	$16 ABCON0 NONE NONE NONE, 4 0
asm: illegal combination: 00072 (<unknown line number>)	PCALIGN	$16 ABCON0 NONE NONE NONE, 4 0
asm: illegal combination: 00072 (<unknown line number>)	PCALIGN	$16 ABCON0 NONE NONE NONE, 4 0
asm: illegal combination: 00032 (<unknown line number>)	PCALIGN	$16 ABCON0 NONE NONE NONE, 4 0
asm: illegal combination: 00032 (<unknown line number>)	PCALIGN	$16 ABCON0 NONE NONE NONE, 4 0
asm: illegal combination: 00032 (<unknown line number>)	PCALIGN	$16 ABCON0 NONE NONE NONE, 4 0
asm: illegal combination: 00032 (<unknown line number>)	PCALIGN	$16 ABCON0 NONE NONE NONE, 4 0
asm: assembly failed

make: *** [my_android_lib.aar] Error 1

Update:

But when I use :
gomobile bind -target=android/arm -tags='headless' -o=$(my_android_lib) -ldflags="-w -X -s" $(my_dir)

the error disappear.

Used commit: 74845437921194633fb106bd3c053561ca7d7f3f

**Comment by klauspost** [comment]
@lizthegrey Can you take a look at this? Seems like a regression from #464

**Comment by lizthegrey** [comment]
I think this is a bug in gomobile rather than a problem with the assembly. PCALIGN is a supported operation in Golang. https://github.com/golang/go/blob/master/src/cmd/internal/obj/arm64/doc.go#L54:L94

**Comment by ICU2020** [comment]
> I think this is a bug in gomobile rather than a problem with the assembly. PCALIGN is a supported operation in Golang. https://github.com/golang/go/blob/master/src/cmd/internal/obj/arm64/doc.go#L54:L94

Is there some ways to walk around?

**Comment by lizthegrey** [comment]
> > I think this is a bug in gomobile rather than a problem with the assembly. PCALIGN is a supported operation in Golang. [golang/go@`master`/src/cmd/internal/obj/arm64/doc.go#L54:L94](https://github.com/golang/go/blob/master/src/cmd/internal/obj/arm64/doc.go?rgh-link-date=2022-10-06T01%3A42%3A18Z#L54:L94)
> 
> Is there some ways to walk around?

I don't believe it's essential to PCALIGN for correctness, only performance. You could try building from a branch with those directives removed, or manually add NOPs to make the alignment work out.

Meanwhile I'd recommend filing a bug upstream on the gomobile component.

**Comment by ICU2020** [comment]
> > > I think this is a bug in gomobile rather than a problem with the assembly. PCALIGN is a supported operation in Golang. [golang/go@`master`/src/cmd/internal/obj/arm64/doc.go#L54:L94](https://github.com/golang/go/blob/master/src/cmd/internal/obj/arm64/doc.go?rgh-link-date=2022-10-06T01%3A42%3A18Z#L54:L94)
> > 
> > 
> > Is there some ways to walk around?
> 
> I don't believe it's essential to PCALIGN for correctness, only performance. You could try building from a branch with those directives removed, or manually add NOPs to make the alignment work out.
> 
> Meanwhile I'd recommend filing a bug upstream on the gomobile component.


Thanks a lot for your response. Could you give some advice which branch I should choose to avoid PCALIGN? Thanks.

**Comment by klauspost** [comment]
@ICU2020 You can build with `-tags=noasm,headless` as a temporary workaround. Feel free to link this issue if you post a bug report for gomobile.
