### ISSUE TITLE
Problem installing this module

### ISSUE THREAD

**Issue by Barceloch** [klauspost/compress#686]
$go install github.com/klauspost/compress@latest
go: downloading github.com/klauspost/compress v1.15.12
go: github.com/klauspost/compress@latest: github.com/klauspost/compress@v1.15.12: read "https:/proxy.golang.org/@v/v1.15.12.zip": read tcp 10.126.120.44:42064->74.125.133.128:443: read: connection reset by peer

some help, there is other way to install it?

**Comment by klauspost** [comment]
This looks like an issue with the proxy you are using.

Can't really help you with that.

**Comment by klauspost** [comment]
@Antonboom Complain to whatever proxy you are using.
