### ISSUE TITLE
Replace with hash/crc32?

### ISSUE THREAD

**Issue by mattes** [klauspost/compress#73]
https://github.com/klauspost/compress/blob/master/gzip/gunzip.go#L17

Can this be replaced with `hash/crc32`? 

Looking at the changelog at https://github.com/klauspost/crc32 and saw that changes have been merged into official go?

Reason why I'm asking, `github.com/klauspost/crc32` seems to be breaking my Google App Engine builds. 

(My deps tree: https://github.com/gavv/httpexpect -> https://github.com/valyala/fasthttp -> https://github.com/klauspost/compress/tree/master/gzip)

**Comment by mattes** [comment]
```
goapp test .
# github.com/klauspost/crc32
../../klauspost/crc32/crc32.go:83: undefined: archAvailableCastagnoli
../../klauspost/crc32/crc32.go:86: undefined: archInitCastagnoli
../../klauspost/crc32/crc32.go:87: undefined: archUpdateCastagnoli
../../klauspost/crc32/crc32.go:107: undefined: archAvailableIEEE
../../klauspost/crc32/crc32.go:110: undefined: archInitIEEE
../../klauspost/crc32/crc32.go:111: undefined: archUpdateIEEE
```

**Comment by mattes** [comment]
ref: https://github.com/klauspost/crc32/issues/7

**Comment by klauspost** [comment]
Yes, you can replace it. It should only make a significant difference if you are using Go 1.6, so I might remove it soon anyway

**Comment by klauspost** [comment]
The package now uses official crc32.
