### ISSUE TITLE
s2.Encode a large value panic

### ISSUE THREAD

**Issue by mYmNeo** [klauspost/compress#778]
I'd wrote a unit test with s2.Encode, found that a panic on such scenario as following
```
v := make([]byte, math.MaxInt32)
if s2.MaxEncodedLen(len(v)) != -1 {
	s2.Encode(nil, v)
}
```
the stack is 
```runtime: g 6: unexpected return pc for github.com/klauspost/compress/s2.encodeBlockAsm called from 0x5000500050005```

**Comment by klauspost** [comment]
Thanks for the report I will check it out!
