### ISSUE TITLE
Error when building flate with gcc-go

### ISSUE THREAD

**Issue by xyproto** [klauspost/compress#78]
When cloning `compress`, entering the `flate` directory and running `go build`, I get the following error messages:

[output.txt](https://github.com/klauspost/compress/files/1077414/output.txt)

This is with: `go version go1.8.1 gccgo (GCC) 7.1.1 20170516 linux/amd64`

**Comment by klauspost** [comment]
This should be fixed by #105 which removes the last assembly.

**Comment by xyproto** [comment]
I just tested with `go version go1.12.2 gccgo (GCC) 9.1.0 linux/amd64`, and it works now. Thanks!
