### ISSUE TITLE
Bug in zstd/best quick reject feature

### ISSUE THREAD

**Issue by greatroar** [klauspost/compress#786]
I just tried the new "best" encoder on some data, and found that it panics with a "slice out of bounds" message. The error occurs on the line

https://github.com/klauspost/compress/blob/2f993587f4d960480c0056fcca379024b18ef0d8/zstd/enc_best.go#L218

where I have

```
len(src)     = 1179648
s            = 1179411
m.length     = 249
m.s          = 1179312
left         = 87
s+m.length-8 = 1179652
```

**Comment by klauspost** [comment]
Oh, so it has been extended that far back.

Good catch.
