### ISSUE TITLE
how to create an empty zlib.reader ?

### ISSUE THREAD

**Issue by bronze1man** [klauspost/compress#79]
I write a memory object pool to reuse some zlib.reader objects.
But I can not find an api to create a empty zlib.reader.
If I pass an empty io.Reader to zlib.NewReader, it will return `unexpected EOF`. 
I can only use lazy init or pass an simple zlib compress output to it to work around this bug right now.

**Comment by klauspost** [comment]
`zlib.NewWriter(nil)` should be fine.  The writer is overwitten by Reset and doesn't appear to be used before you write.

**Comment by bronze1man** [comment]
> zlib.NewWriter(nil) should be fine. The writer is overwitten by Reset and doesn't appear to be used before you write.

I want to init a zlib.reader , not zlib.Write.

**Comment by jonchammer** [comment]
Hello from 2025. 👋 

Very sorry to revive an ancient thread, but just in case anyone else stumbles on this issue, I thought it might be helpful to show that it is possible to use a `zlib.Reader` with a `sync.Pool`. This is how I'm handling it:

```Go
package main

import (
	"bytes"
	"github.com/klauspost/compress/zlib"
	"io"
	"sync"
)

// NOTE: zlib does not return a concrete 'zlib.Reader' type. Instead, it 
// returns a private type that implements this interface.
type zlibReader interface {
	io.ReadCloser
	zlib.Resetter
}

// Minimal valid Zlib bytestream (just the header, no payload)
var zlibHeader = []byte{
	0x78, 0x9C, 0x00, 0x00,
	0x00, 0xFF, 0xFF, 0x03,
	0x00, 0x00, 0x00, 0x00,
	0x01,
}

var zlibReaderPool = sync.Pool{
	New: func() any {
		// NOTE: The zlib library requires the reader to be initialized with
		// a valid Zlib bytestream, even though we plan to overwrite that 
		// stream immediately.
		reader, _ := zlib.NewReader(bytes.NewReader(zlibHeader))
		return reader.(zlibReader)
	},
}

func Decompress(dest io.Writer, src io.Reader) error {

	// Grab an initialized reader from the pool. We'll put it back when we're
	// done with it.
	reader := zlibReaderPool.Get().(zlibReader)
	defer zlibReaderPool.Put(reader)

	// Set 'src' as the source
	if err := reader.Reset(src, nil); err != nil {
		return err
	}

	// Decompress into 'dest'
	if _, err := io.Copy(dest, reader); err != nil {
		return err
	}
	if err := reader.Close(); err != nil {
		return err
	}

	return nil
}

```
