### ISSUE TITLE
Bug in flate?

### ISSUE THREAD

**Issue by gen2brain** [klauspost/compress#82]
Hello,

I am trying to use your library here https://github.com/gen2brain/raylib-go/tree/master/rres/cmd/rrem , to embed game resources in file. I have an issue only with DEFLATE (LZ4, XZ, BZIP2 etc. are ok) and both with your library and official compress/flate, not sure how they are related. 

There is no issue with .wav data for example, that one is ok after compress/uncompress, only with image.Pix data array that I am compressing. This is what I am getting after uncompress http://imagizer.imageshack.com/img924/9867/EZEAmY.png , and it should be like this http://imagizer.imageshack.com/img924/3088/8TwKUa.png . Unfortunately, I don't have small example to reproduce this behaviour.

**Comment by shoenig** [comment]
@gen2brain  it looks like you never call Sync on rresFile - which may mean the program exits before flushing data to the file (deferring only Close doesn't do that for you). May I also suggest breaking this code down into more functions, nobody likes reading a 400 line `main` :face_with_head_bandage:

**Comment by gen2brain** [comment]
Thanks for your time, I will try that. Sorry, this is initial code while I test binary format, it will not look like that at the end.

**Comment by gen2brain** [comment]
I refactored a little https://github.com/gen2brain/raylib-go/blob/master/rres/cmd/rrem/main.go , so it is easier on the eyes, rresFile now  calls Sync() and Close() (not deffered), but same issue, also compress() function now accepts and returns []byte.

**Comment by klauspost** [comment]
At first glance what you are doing seems reasonable. OTOH I would expect this to give problems elsewhere, and it is being used quite a few places. So I am more inclined to believing this is a decoder problem.

You can try to decode the result, it should of course match your input byte-by-byte. 

PS. `flate.BestCompression` may be overkill, the default compression is several times faster and only a tiny bit bigger.

**Comment by gen2brain** [comment]
I have a simple test that you can run.

`package main

import (
	"bytes"
	"fmt"
	"image"
	"image/draw"
	"os"

	_ "image/jpeg"
	_ "image/png"

	"github.com/klauspost/compress/flate"
)

func main() {
	if len(os.Args) != 2 {
		fmt.Println("no argument, it should be .jpg or .png file")
		os.Exit(1)
	}

	file, err := os.Open(os.Args[1])
	if err != nil {
		fmt.Printf("%v\n", err)
		os.Exit(1)
	}

	img, _, err := image.Decode(file)
	if err != nil {
		fmt.Printf("%v\n", err)
		os.Exit(1)
	}

	file.Close()

	rect := img.Bounds()
	i := image.NewNRGBA(rect)
	draw.Draw(i, rect, img, rect.Min, draw.Src)
	data := i.Pix

	size := len(data)
	fmt.Println("original size: ", size)

	buf := new(bytes.Buffer)

	w, err := flate.NewWriter(buf, flate.DefaultCompression)
	if err != nil {
		fmt.Printf("%v\n", err)
		os.Exit(1)
	}

	_, err = w.Write(data)
	if err != nil {
		fmt.Printf("%v\n", err)
		os.Exit(1)
	}

	w.Close()

	compData := buf.Bytes()

	fmt.Println("compressed size: ", len(compData))

	r := flate.NewReader(bytes.NewReader(compData))

	uncompData := make([]byte, size)
	r.Read(uncompData)

	r.Close()

	fmt.Println("uncompressed size: ", len(uncompData))

	if !bytes.Equal(data, uncompData) {
		fmt.Println("not equal!")
		cmp := bytes.Compare(data, uncompData)
		fmt.Println("compare: ", cmp)
	}
}
`

Returns this:
`
original size:  262144
compressed size:  5503
uncompressed size:  262144
not equal
compare:  1
`

**Comment by klauspost** [comment]
Always check your returned values. `r.Read(uncompData)` returns the actual number of filled bytes.

Here is a fixed version: https://gist.github.com/klauspost/d34706eb59da54da93112577f4229106
