### ISSUE TITLE
zstd: invalid memory address or nil pointer dereference

### ISSUE THREAD

**Issue by alasdairforsythe** [klauspost/compress#840]
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0xbf450]

goroutine 1 [running]:
github.com/klauspost/compress/zstd.(*Encoder).EncodeAll(0x0, {0x4019846000, 0x1fbd638, 0x323adf8}, {0x401ca82000, 0x0, 0x1fbd638})
        /root/go/pkg/mod/github.com/klauspost/compress@v1.16.7/zstd/encoder.go:497 +0x100

```
encoder, _ := zstd.NewWriter(nil, zstd.WithEncoderLevel(7))
encoded = encoder.EncodeAll(encoded, make([]byte, 0, len(encoded)))
```

OK, I see the problem is I specified an integer instead of one of your constants. That's good news. Might be worth fixing that, or providing an example as the usage instructions for WithEncoderLevel are not very clear.

**Comment by klauspost** [comment]
No. The problem is that you didn't check the error returned by NewWriter.

Unless I am mistaking it returns `unknown encoder level`.

**Comment by alasdairforsythe** [comment]
It's your project, you can do as you like. However, it'd have saved me the time, and you the time in reading a false positive bug report, if you put up some clearer usage examples. Thanks for your work.

**Comment by klauspost** [comment]
@alasdairforsythe You are welcome :)
