### ISSUE TITLE
type binary.littleEndian has no field or method AppendUint32

### ISSUE THREAD

**Issue by eli1797** [klauspost/compress#863]
Either the v1.17.0 release introduced a bug or I'm making a mistake.

Seeing an error in `github.com/klauspost/compress/zstd`'s dict.go. 

```
out.Write(binary.LittleEndian.AppendUint32(nil, o.ID))

// line 479
// binary.LittleEndian.AppendUint32 undefined (type binary.littleEndian has no field or method AppendUint32)
```

Using go 1.18

**Comment by mYmNeo** [comment]
Release note says it need go1.21.x 😆

**Comment by klauspost** [comment]
Yes. I support two versions back from current Go release. That is one more than Go receives security updates, so you really should upgrade.
