### ISSUE TITLE
brotli support 

### ISSUE THREAD

**Issue by gyf19** [klauspost/compress#9]
It would be nice to have some wrapper or native implementation for golang.

**Comment by klauspost** [comment]
I have considered it, and it is very high on my todo-list.

**Comment by gyf19** [comment]
cool

**Comment by dsnet** [comment]
I finished a complete Brotli decoder: https://github.com/dsnet/compress/brotli

**Comment by CAFxX** [comment]
Shouldn't this be reopened? There's a pure go version [here](https://github.com/andybalholm/brotli) but it's [mechanically translated from C via c2go](https://groups.google.com/forum/#!msg/golang-nuts/J5MwJnmDpOw/yQacKG2pBwAJ) and it's far from being anywhere close in performance with the C version.
