### ISSUE TITLE
Compression rate is different at the same level old vs new

### ISSUE THREAD

**Issue by lulusc** [klauspost/compress#90]
Hi, I did some local benchmark with different types of data and found that with a same compression level, the compression rate is different using old library vs this library. In particular, when I used old library I can achieve a compression rate with level 2 while using this one I need to use level 5. This makes this library actually slower than the old one if we are targeting at a same compression level. Is this a known issue or maybe I'm testing it wrong?

**Comment by godofdream** [comment]
could you add an example?
I would like to verify it.

**Comment by klauspost** [comment]
I have re-run all benchmark with Go 1.10 and updated the performance spreadsheet. See https://github.com/klauspost/compress#performance-update-2018
