### ISSUE TITLE
decoder.DecodeAll return io.UnExpectedEOF instead of nil when input is valid zstd compressed data

### ISSUE THREAD

**Issue by hitzhangjie** [klauspost/compress#909]
in my case, dec.DecodeAll(buf, nil), it's valid zstd compressed data, I think it shouldn't return io.UnExpectedEOF, it should return nil, instead.

But it return io.UnExpectedEOF, if so, how to know the returned decompressed data is good or not.

The code is like:

```go
	dec, err := zstd.NewReader(nil)
	if err != nil {
		panic(err)
	}

	b, err := dec.DecodeAll(input, nil)
	if err != nil && err != io.ErrUnexpectedEOF {
              return
	}
       // process `b`
       ....
```

**Comment by klauspost** [comment]
If it returns `io.ErrUnexpectedEOF` the data is NOT good.

**Comment by hitzhangjie** [comment]
Well, actually the data is really simple:
```go
var s = "hello, i am zstd!"

input = enc.EncodeAll([]byte(s), nil)
```

So far, I use `err != nil && err != io.ErrUnexpectedEOF` to check to work around this problem.

---

By the way, `dec.DecodeAll(input, nil)`, I read this: https://github.com/facebook/zstd/blob/dev/doc/zstd_compression_format.md#frame_content_size,
it means the compressed data may contain the original size `frame_content_size`, it's optional.

Does it mean I could handle off the memory allocation task to the decoder if I do compress and decompress using this same package.

**Comment by klauspost** [comment]
```
package main

import (
	"fmt"

	"github.com/klauspost/compress/zstd"
)

func main() {
	var s = "hello, i am zstd!"
	enc, err := zstd.NewWriter(nil)
	if err != nil {
		panic(err)
	}
	input := enc.EncodeAll([]byte(s), nil)
	dec, err := zstd.NewReader(nil)
	if err != nil {
		panic(err)
	}
	output, err := dec.DecodeAll(input, nil)
	if err != nil {
		panic(err)
	}
	fmt.Println(string(output))
}
```

**Comment by klauspost** [comment]
Please provide an *actual* reproducer.

**Comment by hitzhangjie** [comment]
I know what happended now.

Actually, the data compressed is generated by following:

```
		input := []byte("hello! my name is zstd!")

		enc, err := zstd.NewWriter(nil, zstd.WithEncoderLevel(zstd.SpeedFastest))
		require.Nil(t, err)

		buf := bytes.NewBuffer(nil)
		enc.Reset(buf)

		_, err = enc.Write(input)
		require.Nil(t, err)

		err = enc.Flush()   ===> enc.Close() 
		require.Nil(t, err)

		bb := buf.Bytes()
		println(len(bb))
```

I'm sorry I wrote several tests and forgot it's this one caused this unexpected behavior yesterday.

I made a mistake here, change `enc.Flush()` to `enc.Close()` solved my problem.

**Comment by klauspost** [comment]
Yes. Flush does not indicate EOF - it merely pushes out what you have already sent.

**Comment by vendornltd** [comment]
I realise this is closed but I see the same and I reuse encoders using the Reset() method.  How do avoid this issue without calling Close()?  Wouldn't calling Close() remove the advantages of using Reset()?

**Comment by vendornltd** [comment]
> No. Encoders are kept after Close as noted in the [docs](https://pkg.go.dev/github.com/klauspost/compress/zstd#Encoder.Close)
> 
> Please open a QA topic in https://github.com/klauspost/compress/discussions if you need more details.

Yes, thanks, I realised I was reading the reader docs :) Appologies!
