### ISSUE TITLE
decompression for streaming data in zip

### ISSUE THREAD

**Issue by chenziliang** [klauspost/compress#91]
Hi,

May i ask if the zlib package here supports streaming zip data decompression ?
Imagine there is a streaming of zlib data over a tcp socket, would like to try to use zlib package to do the decompression for data each read from the packet. Pseudo code is as below.

```
for {
   ...
   err := socketconn.Read(data)
   ...
   zlib.Reader(...) // incrementally does the decompression when new data flows in
}
```

Thank you !

**Comment by klauspost** [comment]
Yes, the zlib reader will stream the input by default. If your socket can provide an `io.Reader`, the input will be streamed and decoded as available. Calling `Read` on the zlib.Reader will block until enough data is available.

If you receive "packets", you need something like an `io.Pipe` to make it streaming.

For your example you would need something like:

```
	r, w := io.Pipe()
	go func() {
		for {
			err := socketconn.Read(data)
			
			// FIXME: You need some way to find out how much was read, so you only write the data read
			n, werr := w.Write(data)
			if werr != nil {
			   return
			}
			if err != nil {
				if err != io.EOF {
					w.CloseWithError(err)
				} else {
					w.Close()
				return
			}
		}
	}()
	zr, err := zlib.NewReader(r)
	// FIXME: check err
	
	// zr is your decoded input stream
```

**Comment by chenziliang** [comment]
Thanks so much. Was thinking using a channel to wrap around the packet to simulate streaming
