### ISSUE TITLE
zstd: Another data corruption on SpeedBestCompression level

### ISSUE THREAD

**Issue by MichaelEischer** [klauspost/compress#922]
After a bug report at https://github.com/restic/restic/issues/4677, we've identified that it is caused by the zstd library at the SpeedBestCompression level. Compressing and decompressing it afterwards results in corrupted data. There is no data corruption at the default compression level. I've tested versions v1.17.4 (via restic using Go 1.21.6) and v1.17.5 (using Go 1.21.6).

[minimized.txt](https://github.com/klauspost/compress/files/14143838/minimized.txt) (Minimized using the script from https://github.com/klauspost/compress/issues/875)

Sorry for only bringing bad news, and that just before the weekend :disappointed: .

**Comment by MichaelEischer** [comment]
Apparently, the data corruption was introduced between v1.17.2 and v1.17.3.

**Comment by klauspost** [comment]
Thanks! I will investigate ASAP

**Comment by klauspost** [comment]
(got it replicated, but you are catching me at an unfortunate time and I don't have time to work on a fix until Sunday/Monday)

**Comment by klauspost** [comment]
@MichaelEischer I found the issue and have a fix in #923 

This is a *recoverable* encoding error for once, so if you or anyone else have critical data compressed with this I will be able to detect and correct this issue. If you have such data feel free to attach it here. If there is enough I can build a standalone tool to read and decompress it.

**Comment by klauspost** [comment]
I will release when I've investigated #920

**Comment by MichaelEischer** [comment]
Thanks for the fix :-) !
