### ISSUE TITLE
Affected by zip slip?

### ISSUE THREAD

**Issue by frontierpsycho** [klauspost/compress#93]
I'm not sure if this is the right place to ask, but can you look into whether this library is affected by zip slip? It seems like golang's standard library is. 

https://github.com/snyk/zip-slip-vulnerability

**Comment by klauspost** [comment]
>seems like golang's standard library is

Not directly as far as I can tell. 

As far as I know, you are only vulnerable if you don't sanitize what you get back.

**Comment by frontierpsycho** [comment]
Thanks.
