### ISSUE TITLE
Using KP Compress outside of Golang contexts

### ISSUE THREAD

**Issue by JoeUX** [klauspost/compress#95]
Hi Klaus – Given your recent performance update, is Compress competitive with its C-based counterparts, like zlib and libdeflate? It would be interesting to see benchmarks against them instead of the standard Go library, since zlib is the standard benchmark and libdeflate is a faster, modern reimplementation of zlib. If Compress beats them, how would we use it, for example with nginx?

**Comment by klauspost** [comment]
I don't think there are significant gains. The cgo version (with zlib) has pretty much been the reference, and getting similar performance was the goal. C has a small natural advantage, but this is so close now that at least there is no reason to taint your nice Go code with cgo :)
 
Also, there is the [cloudflare zlib fork](https://github.com/cloudflare/zlib) which brings most of the same stuff to the C-world.

If I can bring myself to finish #60 and #69 - maybe even combining it with dynamic block splitting, we might get a significant speed advantage. But for now, most of the little time I am using on compression is spent on zstd, which Go needs a good native port of.

**Comment by JoeUX** [comment]
Understood. People have had a [hard time](https://community.centminmod.com/threads/please-add-single-threaded-gzip-optimization.8166/) building Cloudflare's optimized fork, but I haven't tried lately. Sometimes Cloudflare just throws things onto GitHub in a way that can't actually be built as-is.

Do you expect AVX2 and BMI instructions to help? I think Vlad Krasnov, one of the CF developers, said something about how AVX2 instructions might beat SSE4.2 for this application, but I don't recall the details. Your benchmarks are on a Sandy Bridge CPU (one of the best Sandy Bridge chips :-), so you don't have AVX2 or BMI, but if you ever upgrade to Haswell or later, it would be interesting if you were able to hit even higher performance. libdeflate [uses AVX2](https://github.com/ebiggers/libdeflate/blob/master/NEWS), but I'm not sure about BMI.

I'm not an advanced developer, but maybe I'll use this as a learning opportunity and see if I can come up with something useful.
