### ISSUE TITLE
Zstd io.ReadCloser made with ZipDecompressor() doesn't consistently consume all compressed data

### ISSUE THREAD

**Issue by vsivsi** [klauspost/compress#954]
***What I expect to happen:***

When `zstd.ZipDecompressor()` is used to make an `io.ReadCloser` that consumes valid compressed data from a provided `io.Reader`, it should consistently consume all of the data written by the zstd compressor that originally produced it. That is, there should be no unread bytes in the input `io.Reader` stream when it is done decompressing.

This is important because this expected behavior is necessary to decompress multiple compressed blobs serially from an `io.Reader` in a streaming fashion. That is, if I have multiple compressed blobs concatenated together, I should be able to decompress one after the next from that input stream without needing to seek or discard unused data from the stream before commencing to decompress the next blob.

***What I often observe happening instead:***

Although I haven't exhaustively tested all possibilities, I have stumbled upon a combination of factors that causes the above expectations to be consistently violated. Specifically, when dictionary compression is performed by the https://github.com/valyala/gozstd library, your library often does not consume all of the compressed data that gozstd produces, yet it somehow seems to always correctly reproduce the decompressed output. The discrepancy always seems to be < 4 bytes, typically 3, so perhaps some kind of optional padding at the end?

I tend to observe this when using the `io.ReadFull()` stdlib function to decompress directly into a `[]byte` that is exactly the size of the original compressed data. That is, increasing the size of the output buffer by even one byte seems to consistently produce the correct expected behavior.

Using `zstd.ZipCompressor()` to generate the compressed data also seems to consistently lead to expected behavior, so perhaps it doesn't output these extra trailing bytes in the first place?

However, using the analogous `gozstd.NewReaderDict()` function always yields the expected behavior (it consistently consumes all compressed data from the input reader).

So, there seems to be some special interaction here with gozstd compressed data.

Thanks for taking a look at this admittedly pretty esoteric issue. There are several workarounds, but it would be very nice not to need to introduce kludges to correctly work around this issue.

Here's my repro, with several rescue cases commented out. The failure is signaled by the panic in the final `if` statement.

```golang
package main

import (
	"bytes"
	"fmt"
	"io"
	"math/rand"
	"os"

	"github.com/klauspost/compress/zstd"
	"github.com/valyala/gozstd"
)

func generateRandomSequence(n int, r *rand.Rand) (s []byte) {
	s = make([]byte, n)
	for i := range s {
		s[i] = [4]byte{'A', 'C', 'G', 'T'}[r.Intn(4)]
	}
	return s
}

func main() {

	const level = 6
	const sampleLen = 1000

	// generate training sequences for zstd dictionary
	rnd := rand.New(rand.NewSource(1234))
	samples := make([][]byte, 32768)
	for i := range samples {
		samples[i] = generateRandomSequence(sampleLen, rnd)
	}

	// use gozstd to build dictionary
	dict := gozstd.BuildDict(samples, 16384)

	// make new sequence data
	data := bytes.NewBuffer(generateRandomSequence(sampleLen, rnd))

	//// compress with gozstd
	cd, err := gozstd.NewCDictLevel(dict, level)
	if err != nil {
		panic(err)
	}
	compZstd := &bytes.Buffer{}
	zstdWriter := gozstd.NewWriterDict(compZstd, cd)
	defer zstdWriter.Release()
	compZstdLen, err := io.Copy(zstdWriter, data)
	if err != nil {
		panic(err)
	}
	if err = zstdWriter.Close(); err != nil {
		panic(err)
	}
	fmt.Printf("gozstd compression %f%%\n", 100.0*(float64(int(compZstdLen)-compZstd.Len())/float64(compZstdLen)))

	//// compress with compress/zstd, using this instead gozstd above rescues
	// compZstd := &bytes.Buffer{}
	// zstdCompressor := zstd.ZipCompressor(zstd.WithEncoderDict(dict), zstd.WithEncoderLevel(zstd.EncoderLevelFromZstd(level)))
	// zstdWriter, err := zstdCompressor(compZstd)
	// if err != nil {
	// 	panic(err)
	// }
	// compZstdLen, err := io.Copy(zstdWriter, data)
	// if err != nil {
	// 	panic(err)
	// }
	// if err = zstdWriter.Close(); err != nil {
	// 	panic(err)
	// }
	// fmt.Printf("zstd compression %f%%\n", 100.0*(float64(int(compZstdLen)-compZstd.Len())/float64(compZstdLen)))

	// Save a copy of gozstd compressed data for later use
	copyCompZstd := make([]byte, compZstd.Len())
	copy(copyCompZstd, compZstd.Bytes())

	// decompress with gozstd (works as expected)
	dd, err := gozstd.NewDDict(dict)
	if err != nil {
		panic(err)
	}
	decompGozstd := make([]byte, sampleLen)
	compGozstdReader := &io.LimitedReader{R: compZstd, N: int64(compZstd.Len())}
	gozstdReader := gozstd.NewReaderDict(compGozstdReader, dd)
	defer gozstdReader.Release()
	decompGozstdLen, err := io.ReadFull(gozstdReader, decompGozstd)
	if err != nil && err != io.ErrUnexpectedEOF {
		panic(err)
	}
	if sampleLen != int64(decompGozstdLen) {
		panic(fmt.Sprintf("Gozstd Length mismatch %d != %d", sampleLen, decompGozstdLen))
	}
	if compGozstdReader.N != 0 {
		panic(fmt.Sprintf("Gozstd didn't consume all data: %d", compGozstdReader.N))
	}

	// decompress with compress/zstd (fails to read all compressed data)
	decompZstd := make([]byte, sampleLen)
	// decompZstd := make([]byte, sampleLen+1)  // Uncomment to rescue

	compZstd = bytes.NewBuffer(copyCompZstd)

	compZstdReader := &io.LimitedReader{R: compZstd, N: int64(compZstd.Len())}
	zstdDecompressor := zstd.ZipDecompressor(zstd.WithDecoderDicts(dict))
	zstdReader := zstdDecompressor(compZstdReader)

	decompZstdLen, err := io.ReadFull(zstdReader, decompZstd)
	if err != nil && err != io.ErrUnexpectedEOF {
		panic(err)
	}
	if sampleLen != decompZstdLen {
		panic(fmt.Sprintf("Zstd Length mismatch %d != %d", sampleLen, decompZstdLen))
	}
	if !bytes.Equal(decompGozstd[:sampleLen], decompZstd[:sampleLen]) {
		panic("Decoded data doesn't match")
	}

	if compZstdReader.N != 0 { // This should panic to reproduce
		panic(fmt.Sprintf("Zstd didn't consume all data: %d", compZstdReader.N))
	}

	os.Exit(0)
}
```

**Comment by klauspost** [comment]
The main issue is that `ReadFull` doesn't read until EOF if the array can be satisfied.

If you change the last part to be...

```Go
	decomp, err := io.ReadAll(zstdReader)
	if err != nil && err != io.ErrUnexpectedEOF {
		panic(err)
	}
	if sampleLen != len(decomp) {
		panic(fmt.Sprintf("Zstd Length mismatch %d != %d", sampleLen, len(decomp)))
	}
	if !bytes.Equal(decompGozstd[:sampleLen], decomp[:sampleLen]) {
		panic("Decoded data doesn't match")
	}
```
Everything will be read from the input.

My guess is that "valyala" adds an empty block with a [Last_Block](https://github.com/facebook/zstd/blob/dev/doc/zstd_compression_format.md#blocks) identifier. This matches with the 3 bytes you see.

Since there is enough data to satisfy your request without decoding more, it will not decode more blocks until the data is actually needed.

You can "reintroduce" the issue by doing `decomp, err := io.ReadAll(&io.LimitedReader{R: zstdReader, N: int64(sampleLen)})` - since the LimitedReader will stop reading upstream once N has been reached.

It is however not my impression the `ZipDecompressor` forces this and creates the problem by itself.

**Comment by vsivsi** [comment]
That all makes perfect sense, thanks so much for quickly responding. Since for my application I know the exact upper bound length of the decompressed data, I can easily work around this by just ensuring the read buffer is strictly longer than that upper bound. 

Given your explanation, the most surprising thing is that the gozstd generated io.Reader *does* consistently consume the input stream to EOF when used with io.ReadFull(). I wonder how does it know to consume that final empty block without peeking ahead (or does it?)

**Comment by klauspost** [comment]
>  I wonder how does it know to consume that final empty block without peeking ahead (or does it?)

TBH I haven't looked into it. It could be that it is trying to always have data decompressed, so it decodes a block as soon as there is no more data available.
