### ISSUE TITLE
zstd decoder sometimes thinks a good file is corrupted

### ISSUE THREAD

**Issue by lance6716** [klauspost/compress#962]
I'm not sure this is caused by wrong usage in caller layer (our application), or a bug in zstd package. Just leave my debug result here

The problem is for a good zstd file the zstd decoder sometimes report the file is corrupted, with many different file offset and error type. like `invalid input: reserved block type encountered` or `tableLog too large`. The decoding concurrency is 4 as default. The problem is gone when I set decoding concurrency to 1.

But I can't reproduce it merely in a unit tests, maybe it's related to go runtime scheduling and our workload from other logic is a must.

I also manually set the `debug` constant to `true` and collected the printed debug log of zstd package. Here are the two debug log that failed on different position. Hope the authors can see some strange behaviour in them. Some lines are printed from irrelevant zstd file and them are mostly printed above the `========================` line.

[stderr1.txt](https://github.com/klauspost/compress/files/15453772/stderr1.txt)
[stderr2.txt](https://github.com/klauspost/compress/files/15453777/stderr2.txt)

**Comment by klauspost** [comment]
Could you share the integration you're doing?

**Comment by lance6716** [comment]
The relevant code is 

https://github.com/pingcap/tidb/blob/57d0b40cd9610351a6769926e5c9e30ddd5f6b7c/br/pkg/storage/writer.go#L96-L111

For this function, the input `io.Reader` maybe reading file on local disk, S3, etc. In my failed case the file is on local disk. And with zstd package now we can support reading the content from zstd files from different storage backends. The next upper layer is a "INSERT INTO" SQL parser, it reads blocks per 5*64*1024 bytes and processes it.

https://github.com/pingcap/tidb/blob/57d0b40cd9610351a6769926e5c9e30ddd5f6b7c/pkg/lightning/mydump/parser.go#L297

**Comment by klauspost** [comment]
I see you implement Seek on `compressReader`.

When you do concurrent decoding, it will do reads async from reads from the decompressed streams, decompressing further than the provided data.

This means that if you seek "underneath" the reader you provide to zstd, it will pick up these seeks at random times, thereby providing broken input to the decompressor.

I can't really tell how safe or unsafe it is done, but it will for sure take some careful writing to make sure that checksums are correct. If you want to do this safely with concurrency (and you provide independent encodes), you should avoid seeking, but instead provide the "seeked" data as a continuous stream.

**Comment by lance6716** [comment]
Thansk for response! I let `Seek` print its arguments, and checked all seek are called with `offset = 0, whence = SeekCurrent`. Not sure I have understand your meaning correctly, but `seek(0, SeekCurrent)` should not interfere with upper layer decoder. However, if I add the print, corruption will not appear (theoretical I can't catch the printing of the failed case). And after I delete the print, the corruption is back. Can reproduce it repeatable.

And in fact `compressReader` only tolerate `seek(0, SeekCurrent)`. https://github.com/pingcap/tidb/blob/57d0b40cd9610351a6769926e5c9e30ddd5f6b7c/br/pkg/storage/compress.go#L133-L139

---

print details:

The printing line is added to the `os.File` wrapper
![image](https://github.com/klauspost/compress/assets/1689766/df338e14-f883-402e-8bb6-a74b56704813)

Then using `grep` to check all lines are `...Seek 0 1`

**Comment by klauspost** [comment]
@lance6716 It is racy either way, since you can be doing the seek while a read is running. So whatever result you'll get will be ambiguous. I don't know the underlying `os.File` well enough to know how it fails when you do both at the same file. Either way you shouldn't be doing it.

You can either add a mutex, so reads and seeks cannot overlap or replace the seek with a counter (either atomic or mutex protected).

**Comment by klauspost** [comment]
@lance6716 Closing for now.
