### ISSUE TITLE
s2: Proposal: Callback when done with EncodeBuffer

### ISSUE THREAD

**Issue by Jille** [klauspost/compress#981]
Buffers given to s2.Writer.EncodeBuffer() can't be touched until a full Flush/Close is done, while the buffer is probably reusable much sooner.

What would you think of a WriterOption that installs a callback that is invoked whenever it is safe to reuse the buffer given to EncodeBuffer?

I'm thinking `func WriterEncodeBufferCallback(callback func([]byte)) WriterOption`.

The common use case would be to return the buffer to a sync.Pool. I want to pass data straight from a ringbuffer-of-bytes into EncodeBuffer and want to know when I can mark it as freed.

I'll be happy to write up the PR if you agree with this proposal.

**Comment by klauspost** [comment]
Seems feasible.

**Comment by klauspost** [comment]
See #842

**Comment by Jille** [comment]
Nice, thank you!
