### ISSUE TITLE
[zip] zip64 extra error has occurred again

### ISSUE THREAD

**Issue by zdz1715** [klauspost/compress#988]
It might be because, in this commit [8411e1d1](https://github.com/klauspost/compress/commit/8411e1d1cc0d8619eb8207d6342fe4878470f7aa)， you restored the following code.

https://github.com/klauspost/compress/commit/8411e1d1cc0d8619eb8207d6342fe4878470f7aa#diff-166bbfc3e1a763faf427c68f9743ff5b98b414a478fc1fba526b062de4247d63L128

**Comment by klauspost** [comment]
@zdz1715 If you submit a PR, please include a regression test.

**Comment by zdz1715** [comment]
> @zdz1715 If you submit a PR, please include a regression test.

I came across this https://github.com/klauspost/compress/issues/623. You fixed this issue at that time, but it was reverted in a later commit https://github.com/klauspost/compress/commit/8411e1d1cc0d8619eb8207d6342fe4878470f7aa#diff-166bbfc3e1a763faf427c68f9743ff5b98b414a478fc1fba526b062de4247d63L128
